import React, { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Wand2, Loader2, Save, Share2 } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { showErrorToastWithCopy } from '@/lib/errorToast';
import { SoundConfig } from './InstrumentSlot';

interface SaveBeatDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  pattern: Record<string, boolean[]>;
  tempo: number;
  instruments: (SoundConfig | null)[];
  userId: string;
  onSaved: (beatId: string, imageUrl?: string, newBeatName?: string, isPublic?: boolean) => void;
  initialBeatName?: string;
  savedBeatId?: string | null;
  isShared?: boolean;
  aiAudioUrl?: string | null;
}

export const SaveBeatDialog: React.FC<SaveBeatDialogProps> = ({
  open,
  onOpenChange,
  pattern,
  tempo,
  instruments,
  userId,
  onSaved,
  initialBeatName = '',
  savedBeatId = null,
  isShared = false,
  aiAudioUrl = null,
}) => {
  const [beatName, setBeatName] = useState('');
  const [isGeneratingName, setIsGeneratingName] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const hasAutoGeneratedRef = React.useRef(false);

  // Sync beatName with initialBeatName when dialog opens
  React.useEffect(() => {
    if (open) {
      setBeatName(initialBeatName);
      hasAutoGeneratedRef.current = false;
    }
  }, [open, initialBeatName]);

  // Auto-generate a name when dialog opens with default name "My Beat" or empty
  // IMPORTANT: Check initialBeatName (the prop) not beatName (state) to avoid race conditions
  React.useEffect(() => {
    if (open && !hasAutoGeneratedRef.current && !isGeneratingName) {
      const trimmedName = initialBeatName.trim().toLowerCase();
      if (trimmedName === 'my beat' || !trimmedName) {
        hasAutoGeneratedRef.current = true;
        generateAIName();
      }
    }
  }, [open, initialBeatName]);

  const generateAIName = async () => {
    setIsGeneratingName(true);
    try {
      // Build a detailed analysis of the beat for AI
      const activeInstruments = instruments.filter(Boolean);
      
      // Count notes per instrument to understand which sounds dominate
      const instrumentNoteCounts: { name: string; soundType: string; noteCount: number }[] = [];
      activeInstruments.forEach((sound, idx) => {
        if (sound && pattern[idx.toString()]) {
          const noteCount = pattern[idx.toString()].filter(Boolean).length;
          instrumentNoteCounts.push({
            name: sound.name,
            soundType: sound.sound_type || 'synth',
            noteCount,
          });
        }
      });
      
      // Sort by note count to identify dominant sounds
      instrumentNoteCounts.sort((a, b) => b.noteCount - a.noteCount);
      
      const totalNotes = instrumentNoteCounts.reduce((sum, i) => sum + i.noteCount, 0);
      const dominantSounds = instrumentNoteCounts.slice(0, 3);
      const backgroundSounds = instrumentNoteCounts.slice(3);
      
      // Analyze rhythm density
      const density = totalNotes > 30 ? 'dense and busy' : totalNotes > 15 ? 'balanced and groovy' : 'sparse and minimal';
      
      // Analyze tempo feel
      let tempoFeel = '';
      if (tempo < 80) tempoFeel = 'slow, chill, laid-back';
      else if (tempo < 100) tempoFeel = 'mid-tempo, smooth, steady';
      else if (tempo < 120) tempoFeel = 'upbeat, energetic';
      else if (tempo < 140) tempoFeel = 'driving, pumping, club-ready';
      else tempoFeel = 'fast, intense, frenetic';
      
      // Build the analysis string
      const dominantDesc = dominantSounds.length > 0 
        ? `The dominant sounds are ${dominantSounds.map(s => `${s.name} (${s.noteCount} notes)`).join(', ')}.`
        : '';
      const backgroundDesc = backgroundSounds.length > 0
        ? `Background elements include ${backgroundSounds.map(s => s.name).join(', ')}.`
        : '';
      
      const prompt = `You are a creative music producer naming beats. Generate ONE unique, catchy, memorable beat name (2-4 words).

BEAT ANALYSIS:
- Tempo: ${tempo} BPM (${tempoFeel})
- Rhythm density: ${density} (${totalNotes} total notes)
- ${dominantDesc}
- ${backgroundDesc}

NAMING GUIDELINES:
- Do NOT just list instruments (bad: "Kick Snare Beat")
- Focus on the VIBE, MOOD, and FEELING the sounds create together
- Use creative metaphors, places, times of day, emotions, or imagery
- Examples of good names: "Midnight Prowl", "Golden Hour", "Basement Bounce", "Velvet Thunder", "Neon Daydream", "Pocket Rocket", "Sunday Sauce", "Electric Honey"
- Be playful, evocative, and memorable
- Consider what genre/mood the tempo and instruments suggest

Return ONLY the beat name, nothing else.`;

      const response = await supabase.functions.invoke('lovable-ai', {
        body: {
          messages: [{ role: 'user', content: prompt }],
          model: 'google/gemini-2.5-flash',
        },
      });

      if (response.error) throw response.error;
      
      const name = response.data?.content?.trim() || 'Untitled Groove';
      // Clean up any quotes or extra punctuation
      setBeatName(name.replace(/["'*_#]/g, '').trim().substring(0, 50));
    } catch (error) {
      console.error('Error generating name:', error);
      showErrorToastWithCopy('Generate Beat Name', error);
    } finally {
      setIsGeneratingName(false);
    }
  };

  const handleSave = async (isPublic: boolean) => {
    if (!beatName.trim()) {
      showErrorToastWithCopy('Save Beat', 'Please enter a name for your beat');
      return;
    }

    setIsSaving(true);
    try {
      // Convert pattern to use sound IDs for storage
      const patternWithIds: Record<string, boolean[]> = {};
      // Build instrument order array to preserve display order
      const instrumentOrder: string[] = [];
      
      instruments.forEach((sound, idx) => {
        if (sound && pattern[idx.toString()]) {
          patternWithIds[sound.id] = pattern[idx.toString()];
          instrumentOrder.push(sound.id);
        }
      });

      let resultId = savedBeatId;

      if (savedBeatId) {
        // Update existing beat
        const { error } = await supabase
          .from('beat_pad_creations')
          .update({
            name: beatName.trim(),
            pattern: patternWithIds,
            tempo,
            is_public: isPublic,
            ai_audio_url: aiAudioUrl,
            instrument_order: instrumentOrder,
          })
          .eq('id', savedBeatId);
        
        if (error) throw error;
        toast.success(isPublic ? 'Beat updated & shared! 🎉' : 'Beat saved!');
      } else {
        // Insert new beat
        const { data, error } = await supabase
          .from('beat_pad_creations')
          .insert({
            creator_id: userId,
            name: beatName.trim(),
            pattern: patternWithIds,
            tempo,
            is_public: isPublic,
            ai_audio_url: aiAudioUrl,
            instrument_order: instrumentOrder,
          })
          .select('id')
          .single();

        if (error) throw error;
        resultId = data.id;
        
        toast.success(isPublic ? 'Beat shared with community! 🎉' : 'Beat saved!');
        toast.info('Generating cover art...', { duration: 3000 });
        
        // Generate AI image in background for new beats
        const instrumentNames = instruments.filter(Boolean).map(i => i!.name);
        supabase.functions.invoke('generate-beat-image', {
          body: {
            beatId: data.id,
            beatName: beatName.trim(),
            instruments: instrumentNames,
            tempo,
            pattern: patternWithIds,
          },
        }).then((res) => {
          if (res.error) {
            console.error('Image generation failed:', res.error);
          } else {
            toast.success('Cover art generated! 🎨');
          }
        }).catch(console.error);
      }
      
      onSaved(resultId!, undefined, beatName.trim(), isPublic);
      onOpenChange(false);
    } catch (error) {
      console.error('Error saving beat:', error);
      showErrorToastWithCopy('Save Beat', error);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Save Your Beat</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="beatName">Beat Name</Label>
            <div className="flex gap-2">
              <Input
                id="beatName"
                value={beatName}
                onChange={(e) => setBeatName(e.target.value)}
                placeholder="Enter a name for your beat..."
                maxLength={50}
                className="flex-1"
              />
              <Button
                variant="outline"
                size="icon"
                onClick={generateAIName}
                disabled={isGeneratingName}
                title="Generate AI name"
              >
                {isGeneratingName ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Wand2 className="h-4 w-4" />
                )}
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              Click the magic wand to let AI name your beat!
            </p>
          </div>

          <div className="bg-muted/50 rounded-lg p-3">
            <p className="text-sm text-muted-foreground">
              <strong>Tempo:</strong> {tempo} BPM
            </p>
            <p className="text-sm text-muted-foreground">
              <strong>Instruments:</strong> {instruments.filter(Boolean).length}
            </p>
            <p className="text-sm text-muted-foreground">
              <strong>Notes:</strong> {Object.values(pattern).reduce((sum, steps) => 
                sum + steps.filter(Boolean).length, 0
              )}
            </p>
          </div>
        </div>

        <DialogFooter className="flex gap-2 sm:gap-2">
          <Button
            variant="outline"
            onClick={() => handleSave(false)}
            disabled={isSaving || !beatName.trim()}
          >
            {isSaving ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <Save className="h-4 w-4 mr-2" />
            )}
            Save Private
          </Button>
          <Button
            onClick={() => handleSave(true)}
            disabled={isSaving || !beatName.trim()}
          >
            {isSaving ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <Share2 className="h-4 w-4 mr-2" />
            )}
            Share to Community
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default SaveBeatDialog;
