import * as React from "react";
import { useState, useMemo } from "react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { X } from "lucide-react";

const EMOJI_DATA = [
  { emoji: "🏠", keywords: ["home", "house", "building"] },
  { emoji: "🏡", keywords: ["home", "house", "garden"] },
  { emoji: "📱", keywords: ["phone", "mobile", "cell"] },
  { emoji: "💻", keywords: ["computer", "laptop", "tech"] },
  { emoji: "🎮", keywords: ["game", "gaming", "controller", "play"] },
  { emoji: "🎨", keywords: ["art", "paint", "creative", "color"] },
  { emoji: "🎵", keywords: ["music", "song", "audio", "sound"] },
  { emoji: "🎬", keywords: ["movie", "film", "video", "cinema"] },
  { emoji: "📚", keywords: ["book", "books", "read", "library", "education"] },
  { emoji: "📖", keywords: ["book", "read", "open"] },
  { emoji: "✏️", keywords: ["pencil", "write", "edit", "draw"] },
  { emoji: "📝", keywords: ["note", "memo", "write", "document"] },
  { emoji: "📅", keywords: ["calendar", "date", "schedule", "event"] },
  { emoji: "📆", keywords: ["calendar", "date", "schedule"] },
  { emoji: "🗓️", keywords: ["calendar", "schedule", "planner"] },
  { emoji: "⏰", keywords: ["clock", "time", "alarm"] },
  { emoji: "🕐", keywords: ["clock", "time", "hour"] },
  { emoji: "⭐", keywords: ["star", "favorite", "best"] },
  { emoji: "🌟", keywords: ["star", "sparkle", "shine", "special"] },
  { emoji: "💫", keywords: ["star", "dizzy", "sparkle"] },
  { emoji: "✨", keywords: ["sparkle", "shine", "magic", "special"] },
  { emoji: "❤️", keywords: ["heart", "love", "like", "favorite"] },
  { emoji: "💖", keywords: ["heart", "love", "sparkle"] },
  { emoji: "💝", keywords: ["heart", "gift", "love"] },
  { emoji: "🧡", keywords: ["heart", "orange", "love"] },
  { emoji: "💛", keywords: ["heart", "yellow", "love"] },
  { emoji: "💚", keywords: ["heart", "green", "love"] },
  { emoji: "💙", keywords: ["heart", "blue", "love"] },
  { emoji: "💜", keywords: ["heart", "purple", "love"] },
  { emoji: "🖤", keywords: ["heart", "black", "love"] },
  { emoji: "🤍", keywords: ["heart", "white", "love"] },
  { emoji: "🤎", keywords: ["heart", "brown", "love"] },
  { emoji: "😀", keywords: ["smile", "happy", "face", "grin"] },
  { emoji: "😃", keywords: ["smile", "happy", "face"] },
  { emoji: "😄", keywords: ["smile", "happy", "laugh"] },
  { emoji: "😁", keywords: ["smile", "grin", "happy"] },
  { emoji: "😊", keywords: ["smile", "blush", "happy", "warm"] },
  { emoji: "🥰", keywords: ["love", "heart", "happy", "adore"] },
  { emoji: "😍", keywords: ["love", "heart", "eyes", "adore"] },
  { emoji: "🤩", keywords: ["star", "eyes", "excited", "wow"] },
  { emoji: "😎", keywords: ["cool", "sunglasses", "awesome"] },
  { emoji: "🤗", keywords: ["hug", "happy", "warm"] },
  { emoji: "🙂", keywords: ["smile", "slight", "okay"] },
  { emoji: "👋", keywords: ["wave", "hello", "hi", "bye", "hand"] },
  { emoji: "👍", keywords: ["thumbs", "up", "good", "like", "yes"] },
  { emoji: "👎", keywords: ["thumbs", "down", "bad", "dislike", "no"] },
  { emoji: "👏", keywords: ["clap", "applause", "bravo"] },
  { emoji: "🙌", keywords: ["hands", "celebration", "hooray"] },
  { emoji: "🤝", keywords: ["handshake", "deal", "agree", "partner"] },
  { emoji: "🙏", keywords: ["pray", "prayer", "hands", "please", "thank you", "folded", "namaste", "hope", "faith", "grateful"] },
  { emoji: "✋", keywords: ["hand", "stop", "high five"] },
  { emoji: "🖐️", keywords: ["hand", "five", "fingers"] },
  { emoji: "👆", keywords: ["point", "up", "finger"] },
  { emoji: "👇", keywords: ["point", "down", "finger"] },
  { emoji: "👈", keywords: ["point", "left", "finger"] },
  { emoji: "👉", keywords: ["point", "right", "finger"] },
  { emoji: "🕊️", keywords: ["dove", "peace", "bird", "holy", "spirit", "faith"] },
  { emoji: "✝️", keywords: ["cross", "christian", "religion", "faith", "jesus"] },
  { emoji: "☮️", keywords: ["peace", "symbol", "love"] },
  { emoji: "🕯️", keywords: ["candle", "prayer", "light", "memorial", "vigil"] },
  { emoji: "😇", keywords: ["angel", "halo", "innocent", "blessed", "holy"] },
  { emoji: "👼", keywords: ["angel", "baby", "cherub", "blessed"] },
  { emoji: "🏃", keywords: ["run", "runner", "exercise", "sport"] },
  { emoji: "🚶", keywords: ["walk", "walking", "person"] },
  { emoji: "💃", keywords: ["dance", "dancer", "party"] },
  { emoji: "🕺", keywords: ["dance", "dancer", "party", "disco"] },
  { emoji: "🧘", keywords: ["yoga", "meditation", "zen", "calm"] },
  { emoji: "🏋️", keywords: ["gym", "weight", "exercise", "fitness"] },
  { emoji: "🚗", keywords: ["car", "drive", "vehicle", "auto"] },
  { emoji: "🚕", keywords: ["taxi", "cab", "car"] },
  { emoji: "🚌", keywords: ["bus", "transport", "vehicle"] },
  { emoji: "🚎", keywords: ["trolley", "bus", "transport"] },
  { emoji: "🏎️", keywords: ["race", "car", "fast", "speed"] },
  { emoji: "🚀", keywords: ["rocket", "space", "launch", "fast"] },
  { emoji: "✈️", keywords: ["plane", "airplane", "flight", "travel"] },
  { emoji: "🛫", keywords: ["plane", "takeoff", "departure"] },
  { emoji: "🛬", keywords: ["plane", "landing", "arrival"] },
  { emoji: "🚁", keywords: ["helicopter", "fly", "aircraft"] },
  { emoji: "🚂", keywords: ["train", "locomotive", "transport"] },
  { emoji: "🚃", keywords: ["train", "railway", "car"] },
  { emoji: "🚄", keywords: ["train", "bullet", "fast", "rail"] },
  { emoji: "🛒", keywords: ["cart", "shop", "shopping", "store", "buy"] },
  { emoji: "🛍️", keywords: ["bag", "shopping", "store", "buy"] },
  { emoji: "💰", keywords: ["money", "bag", "dollar", "rich"] },
  { emoji: "💵", keywords: ["money", "dollar", "cash", "bill"] },
  { emoji: "💳", keywords: ["card", "credit", "payment", "buy"] },
  { emoji: "🎁", keywords: ["gift", "present", "birthday", "surprise"] },
  { emoji: "🎈", keywords: ["balloon", "party", "celebration"] },
  { emoji: "🎉", keywords: ["party", "celebration", "confetti", "tada"] },
  { emoji: "🎊", keywords: ["confetti", "celebration", "party"] },
  { emoji: "🎂", keywords: ["cake", "birthday", "celebration"] },
  { emoji: "🍰", keywords: ["cake", "dessert", "sweet"] },
  { emoji: "🧁", keywords: ["cupcake", "dessert", "sweet"] },
  { emoji: "🍕", keywords: ["pizza", "food", "slice"] },
  { emoji: "🍔", keywords: ["burger", "hamburger", "food"] },
  { emoji: "🍟", keywords: ["fries", "french", "food"] },
  { emoji: "🌭", keywords: ["hotdog", "food", "sausage"] },
  { emoji: "🥪", keywords: ["sandwich", "food", "lunch"] },
  { emoji: "🌮", keywords: ["taco", "food", "mexican"] },
  { emoji: "🌯", keywords: ["burrito", "food", "wrap"] },
  { emoji: "🥗", keywords: ["salad", "healthy", "food", "green"] },
  { emoji: "🍜", keywords: ["noodles", "ramen", "food", "asian"] },
  { emoji: "🍝", keywords: ["pasta", "spaghetti", "food", "italian"] },
  { emoji: "🍣", keywords: ["sushi", "food", "japanese", "fish"] },
  { emoji: "🍦", keywords: ["ice cream", "dessert", "sweet", "cold"] },
  { emoji: "🍩", keywords: ["donut", "doughnut", "dessert", "sweet"] },
  { emoji: "🍪", keywords: ["cookie", "dessert", "sweet", "biscuit"] },
  { emoji: "☕", keywords: ["coffee", "drink", "hot", "cafe", "cup"] },
  { emoji: "🍵", keywords: ["tea", "drink", "hot", "cup"] },
  { emoji: "🥤", keywords: ["drink", "soda", "cup", "beverage"] },
  { emoji: "🧃", keywords: ["juice", "box", "drink"] },
  { emoji: "🍷", keywords: ["wine", "drink", "alcohol", "glass"] },
  { emoji: "🍺", keywords: ["beer", "drink", "alcohol", "mug"] },
  { emoji: "🐶", keywords: ["dog", "puppy", "pet", "animal"] },
  { emoji: "🐱", keywords: ["cat", "kitty", "pet", "animal"] },
  { emoji: "🐭", keywords: ["mouse", "animal", "rodent"] },
  { emoji: "🐹", keywords: ["hamster", "pet", "animal"] },
  { emoji: "🐰", keywords: ["rabbit", "bunny", "animal"] },
  { emoji: "🦊", keywords: ["fox", "animal", "wild"] },
  { emoji: "🐻", keywords: ["bear", "animal", "wild"] },
  { emoji: "🐼", keywords: ["panda", "bear", "animal"] },
  { emoji: "🐨", keywords: ["koala", "animal", "australia"] },
  { emoji: "🐯", keywords: ["tiger", "animal", "wild", "cat"] },
  { emoji: "🦁", keywords: ["lion", "animal", "wild", "cat"] },
  { emoji: "🐮", keywords: ["cow", "animal", "farm"] },
  { emoji: "🐷", keywords: ["pig", "animal", "farm"] },
  { emoji: "🐸", keywords: ["frog", "animal", "green"] },
  { emoji: "🐵", keywords: ["monkey", "animal", "ape"] },
  { emoji: "🐔", keywords: ["chicken", "animal", "farm", "bird"] },
  { emoji: "🐧", keywords: ["penguin", "animal", "bird", "cold"] },
  { emoji: "🐦", keywords: ["bird", "animal", "fly"] },
  { emoji: "🦋", keywords: ["butterfly", "insect", "pretty"] },
  { emoji: "🐝", keywords: ["bee", "insect", "honey"] },
  { emoji: "🌸", keywords: ["flower", "blossom", "cherry", "spring"] },
  { emoji: "🌺", keywords: ["flower", "hibiscus", "tropical"] },
  { emoji: "🌻", keywords: ["flower", "sunflower", "yellow"] },
  { emoji: "🌹", keywords: ["rose", "flower", "red", "love"] },
  { emoji: "🌷", keywords: ["tulip", "flower", "spring"] },
  { emoji: "🌼", keywords: ["flower", "blossom", "daisy"] },
  { emoji: "🌱", keywords: ["plant", "seedling", "grow", "garden"] },
  { emoji: "🌲", keywords: ["tree", "evergreen", "nature", "forest"] },
  { emoji: "🌳", keywords: ["tree", "nature", "forest", "deciduous"] },
  { emoji: "🌴", keywords: ["palm", "tree", "tropical", "beach"] },
  { emoji: "🌵", keywords: ["cactus", "desert", "plant"] },
  { emoji: "🍀", keywords: ["clover", "luck", "lucky", "four leaf"] },
  { emoji: "🍁", keywords: ["leaf", "maple", "fall", "autumn"] },
  { emoji: "🍂", keywords: ["leaves", "fall", "autumn"] },
  { emoji: "🍃", keywords: ["leaf", "wind", "nature"] },
  { emoji: "☀️", keywords: ["sun", "sunny", "weather", "bright"] },
  { emoji: "🌙", keywords: ["moon", "night", "crescent"] },
  { emoji: "⭐", keywords: ["star", "night", "sky"] },
  { emoji: "🌈", keywords: ["rainbow", "color", "weather"] },
  { emoji: "☁️", keywords: ["cloud", "weather", "sky"] },
  { emoji: "⛅", keywords: ["cloud", "sun", "weather"] },
  { emoji: "🌧️", keywords: ["rain", "weather", "cloud"] },
  { emoji: "⛈️", keywords: ["storm", "thunder", "weather"] },
  { emoji: "❄️", keywords: ["snow", "winter", "cold", "ice"] },
  { emoji: "🔥", keywords: ["fire", "hot", "flame", "lit"] },
  { emoji: "💧", keywords: ["water", "drop", "liquid"] },
  { emoji: "🌊", keywords: ["wave", "ocean", "sea", "water"] },
  { emoji: "🏖️", keywords: ["beach", "vacation", "summer", "sand"] },
  { emoji: "🏕️", keywords: ["camp", "camping", "tent", "outdoor"] },
  { emoji: "🏔️", keywords: ["mountain", "snow", "nature"] },
  { emoji: "⛰️", keywords: ["mountain", "nature", "hike"] },
  { emoji: "🗻", keywords: ["mountain", "fuji", "japan"] },
  { emoji: "🏠", keywords: ["house", "home", "building"] },
  { emoji: "🏢", keywords: ["building", "office", "work"] },
  { emoji: "🏥", keywords: ["hospital", "health", "medical"] },
  { emoji: "🏫", keywords: ["school", "education", "building"] },
  { emoji: "🏛️", keywords: ["museum", "building", "classical"] },
  { emoji: "⛪", keywords: ["church", "religion", "building"] },
  { emoji: "🕌", keywords: ["mosque", "religion", "building"] },
  { emoji: "🏪", keywords: ["store", "shop", "convenience"] },
  { emoji: "🏬", keywords: ["mall", "store", "department"] },
  { emoji: "🗼", keywords: ["tower", "tokyo", "landmark"] },
  { emoji: "🗽", keywords: ["statue", "liberty", "landmark"] },
  { emoji: "⚽", keywords: ["soccer", "football", "sport", "ball"] },
  { emoji: "🏀", keywords: ["basketball", "sport", "ball"] },
  { emoji: "🏈", keywords: ["football", "sport", "american"] },
  { emoji: "⚾", keywords: ["baseball", "sport", "ball"] },
  { emoji: "🎾", keywords: ["tennis", "sport", "ball"] },
  { emoji: "🏐", keywords: ["volleyball", "sport", "ball"] },
  { emoji: "🏓", keywords: ["ping pong", "table tennis", "sport"] },
  { emoji: "🎯", keywords: ["target", "dart", "bullseye", "goal"] },
  { emoji: "🎳", keywords: ["bowling", "sport", "pins"] },
  { emoji: "🎲", keywords: ["dice", "game", "random", "luck"] },
  { emoji: "🧩", keywords: ["puzzle", "game", "piece"] },
  { emoji: "♟️", keywords: ["chess", "game", "strategy"] },
  { emoji: "🎭", keywords: ["theater", "drama", "mask", "arts"] },
  { emoji: "🎪", keywords: ["circus", "tent", "entertainment"] },
  { emoji: "🎤", keywords: ["microphone", "sing", "karaoke", "music"] },
  { emoji: "🎧", keywords: ["headphones", "music", "listen", "audio"] },
  { emoji: "🎸", keywords: ["guitar", "music", "rock", "instrument"] },
  { emoji: "🎹", keywords: ["piano", "keyboard", "music", "instrument"] },
  { emoji: "🥁", keywords: ["drum", "music", "instrument"] },
  { emoji: "🎺", keywords: ["trumpet", "music", "brass", "instrument"] },
  { emoji: "🎻", keywords: ["violin", "music", "string", "instrument"] },
  { emoji: "📷", keywords: ["camera", "photo", "picture"] },
  { emoji: "📸", keywords: ["camera", "flash", "photo"] },
  { emoji: "📹", keywords: ["video", "camera", "record"] },
  { emoji: "🎥", keywords: ["movie", "camera", "film"] },
  { emoji: "📺", keywords: ["tv", "television", "watch"] },
  { emoji: "📻", keywords: ["radio", "music", "listen"] },
  { emoji: "🔔", keywords: ["bell", "notification", "alert", "ring"] },
  { emoji: "🔕", keywords: ["bell", "mute", "silent"] },
  { emoji: "📢", keywords: ["megaphone", "announcement", "loud"] },
  { emoji: "📣", keywords: ["megaphone", "cheer", "announcement"] },
  { emoji: "💬", keywords: ["speech", "bubble", "talk", "chat", "message"] },
  { emoji: "💭", keywords: ["thought", "bubble", "think"] },
  { emoji: "🗨️", keywords: ["speech", "bubble", "left"] },
  { emoji: "🗯️", keywords: ["anger", "bubble", "mad"] },
  { emoji: "✉️", keywords: ["email", "mail", "letter", "envelope"] },
  { emoji: "📧", keywords: ["email", "mail", "electronic"] },
  { emoji: "📨", keywords: ["envelope", "incoming", "mail"] },
  { emoji: "📩", keywords: ["envelope", "arrow", "mail"] },
  { emoji: "📮", keywords: ["mailbox", "post", "mail"] },
  { emoji: "📦", keywords: ["package", "box", "delivery", "ship"] },
  { emoji: "📋", keywords: ["clipboard", "list", "document"] },
  { emoji: "📁", keywords: ["folder", "file", "document"] },
  { emoji: "📂", keywords: ["folder", "open", "file"] },
  { emoji: "🗂️", keywords: ["folder", "divider", "organize"] },
  { emoji: "📊", keywords: ["chart", "graph", "data", "stats"] },
  { emoji: "📈", keywords: ["chart", "graph", "up", "increase"] },
  { emoji: "📉", keywords: ["chart", "graph", "down", "decrease"] },
  { emoji: "🔍", keywords: ["search", "magnify", "look", "find"] },
  { emoji: "🔎", keywords: ["search", "magnify", "right"] },
  { emoji: "🔐", keywords: ["lock", "key", "secure", "password"] },
  { emoji: "🔒", keywords: ["lock", "secure", "closed"] },
  { emoji: "🔓", keywords: ["lock", "unlock", "open"] },
  { emoji: "🔑", keywords: ["key", "lock", "password", "access"] },
  { emoji: "🛠️", keywords: ["tools", "wrench", "hammer", "fix"] },
  { emoji: "🔧", keywords: ["wrench", "tool", "fix"] },
  { emoji: "🔨", keywords: ["hammer", "tool", "build"] },
  { emoji: "⚙️", keywords: ["gear", "settings", "cog", "config"] },
  { emoji: "🧲", keywords: ["magnet", "attract"] },
  { emoji: "💡", keywords: ["light", "bulb", "idea", "bright"] },
  { emoji: "🔦", keywords: ["flashlight", "light", "torch"] },
  { emoji: "🕯️", keywords: ["candle", "light", "flame"] },
  { emoji: "📌", keywords: ["pin", "location", "pushpin"] },
  { emoji: "📍", keywords: ["pin", "location", "map", "place"] },
  { emoji: "🗺️", keywords: ["map", "world", "travel"] },
  { emoji: "🧭", keywords: ["compass", "direction", "navigate"] },
  { emoji: "🚩", keywords: ["flag", "red", "mark"] },
  { emoji: "🏁", keywords: ["flag", "checkered", "finish", "race"] },
  { emoji: "🎌", keywords: ["flag", "japan", "crossed"] },
  { emoji: "🏳️", keywords: ["flag", "white", "surrender"] },
  { emoji: "🏴", keywords: ["flag", "black"] },
  { emoji: "⚠️", keywords: ["warning", "caution", "alert"] },
  { emoji: "🚫", keywords: ["no", "forbidden", "prohibited"] },
  { emoji: "⛔", keywords: ["stop", "no entry", "forbidden"] },
  { emoji: "❌", keywords: ["x", "cross", "no", "wrong", "delete"] },
  { emoji: "⭕", keywords: ["circle", "o", "ring"] },
  { emoji: "✅", keywords: ["check", "yes", "done", "complete"] },
  { emoji: "☑️", keywords: ["check", "box", "vote"] },
  { emoji: "✔️", keywords: ["check", "tick", "yes", "correct"] },
  { emoji: "❓", keywords: ["question", "help", "ask"] },
  { emoji: "❔", keywords: ["question", "white"] },
  { emoji: "❗", keywords: ["exclamation", "important", "alert"] },
  { emoji: "❕", keywords: ["exclamation", "white"] },
  { emoji: "➕", keywords: ["plus", "add", "new"] },
  { emoji: "➖", keywords: ["minus", "subtract", "remove"] },
  { emoji: "➗", keywords: ["divide", "division", "math"] },
  { emoji: "✖️", keywords: ["multiply", "x", "times"] },
  { emoji: "💯", keywords: ["hundred", "perfect", "score", "100"] },
  { emoji: "🔢", keywords: ["numbers", "123", "count"] },
  { emoji: "🔤", keywords: ["letters", "abc", "alphabet"] },
  { emoji: "🔠", keywords: ["letters", "uppercase", "capital"] },
  { emoji: "🔡", keywords: ["letters", "lowercase", "small"] },
  { emoji: "ℹ️", keywords: ["info", "information", "help"] },
  { emoji: "🆕", keywords: ["new", "fresh", "latest"] },
  { emoji: "🆓", keywords: ["free", "gratis"] },
  { emoji: "🆗", keywords: ["ok", "okay", "button"] },
  { emoji: "🆙", keywords: ["up", "button", "level"] },
  { emoji: "🔙", keywords: ["back", "arrow", "return"] },
  { emoji: "🔚", keywords: ["end", "arrow"] },
  { emoji: "🔛", keywords: ["on", "arrow"] },
  { emoji: "🔜", keywords: ["soon", "arrow"] },
  { emoji: "🔝", keywords: ["top", "arrow", "up"] },
  { emoji: "⬆️", keywords: ["up", "arrow", "north"] },
  { emoji: "⬇️", keywords: ["down", "arrow", "south"] },
  { emoji: "⬅️", keywords: ["left", "arrow", "west"] },
  { emoji: "➡️", keywords: ["right", "arrow", "east"] },
  { emoji: "↗️", keywords: ["arrow", "northeast", "up right"] },
  { emoji: "↘️", keywords: ["arrow", "southeast", "down right"] },
  { emoji: "↙️", keywords: ["arrow", "southwest", "down left"] },
  { emoji: "↖️", keywords: ["arrow", "northwest", "up left"] },
  { emoji: "↕️", keywords: ["arrow", "up down", "vertical"] },
  { emoji: "↔️", keywords: ["arrow", "left right", "horizontal"] },
  { emoji: "🔀", keywords: ["shuffle", "random", "mix"] },
  { emoji: "🔁", keywords: ["repeat", "loop", "replay"] },
  { emoji: "🔂", keywords: ["repeat", "one", "single"] },
  { emoji: "▶️", keywords: ["play", "start", "forward"] },
  { emoji: "⏸️", keywords: ["pause", "stop", "wait"] },
  { emoji: "⏹️", keywords: ["stop", "end"] },
  { emoji: "⏺️", keywords: ["record", "dot"] },
  { emoji: "⏭️", keywords: ["next", "forward", "skip"] },
  { emoji: "⏮️", keywords: ["previous", "back", "rewind"] },
  { emoji: "🔴", keywords: ["red", "circle", "dot"] },
  { emoji: "🟠", keywords: ["orange", "circle", "dot"] },
  { emoji: "🟡", keywords: ["yellow", "circle", "dot"] },
  { emoji: "🟢", keywords: ["green", "circle", "dot"] },
  { emoji: "🔵", keywords: ["blue", "circle", "dot"] },
  { emoji: "🟣", keywords: ["purple", "circle", "dot"] },
  { emoji: "🟤", keywords: ["brown", "circle", "dot"] },
  { emoji: "⚫", keywords: ["black", "circle", "dot"] },
  { emoji: "⚪", keywords: ["white", "circle", "dot"] },
  { emoji: "🟥", keywords: ["red", "square"] },
  { emoji: "🟧", keywords: ["orange", "square"] },
  { emoji: "🟨", keywords: ["yellow", "square"] },
  { emoji: "🟩", keywords: ["green", "square"] },
  { emoji: "🟦", keywords: ["blue", "square"] },
  { emoji: "🟪", keywords: ["purple", "square"] },
  { emoji: "🟫", keywords: ["brown", "square"] },
  { emoji: "⬛", keywords: ["black", "square"] },
  { emoji: "⬜", keywords: ["white", "square"] },
  { emoji: "👨‍👩‍👧", keywords: ["family", "parents", "child"] },
  { emoji: "👨‍👩‍👦", keywords: ["family", "parents", "child", "boy"] },
  { emoji: "👪", keywords: ["family", "parents", "child"] },
  { emoji: "👥", keywords: ["people", "group", "community"] },
  { emoji: "👤", keywords: ["person", "user", "profile"] },
  { emoji: "🧑‍🤝‍🧑", keywords: ["people", "holding hands", "together"] },
  { emoji: "👫", keywords: ["couple", "holding hands", "together"] },
  { emoji: "👭", keywords: ["women", "holding hands", "friends"] },
  { emoji: "👬", keywords: ["men", "holding hands", "friends"] },
  { emoji: "🧑‍🦱", keywords: ["person", "curly hair"] },
  { emoji: "🧑‍🦰", keywords: ["person", "red hair", "ginger"] },
  { emoji: "🧑‍🦳", keywords: ["person", "white hair", "gray"] },
  { emoji: "🧑‍🦲", keywords: ["person", "bald"] },
  { emoji: "👶", keywords: ["baby", "child", "infant"] },
  { emoji: "🧒", keywords: ["child", "kid", "young"] },
  { emoji: "👦", keywords: ["boy", "child", "young"] },
  { emoji: "👧", keywords: ["girl", "child", "young"] },
  { emoji: "🧑", keywords: ["person", "adult"] },
  { emoji: "👨", keywords: ["man", "adult", "male"] },
  { emoji: "👩", keywords: ["woman", "adult", "female"] },
  { emoji: "🧓", keywords: ["older", "adult", "elder"] },
  { emoji: "👴", keywords: ["old", "man", "grandfather"] },
  { emoji: "👵", keywords: ["old", "woman", "grandmother"] },
  { emoji: "🧑‍⚕️", keywords: ["doctor", "health", "medical", "nurse"] },
  { emoji: "👨‍⚕️", keywords: ["doctor", "man", "health"] },
  { emoji: "👩‍⚕️", keywords: ["doctor", "woman", "health"] },
  { emoji: "🧑‍🎓", keywords: ["student", "graduate", "education"] },
  { emoji: "👨‍🎓", keywords: ["student", "man", "graduate"] },
  { emoji: "👩‍🎓", keywords: ["student", "woman", "graduate"] },
  { emoji: "🧑‍🏫", keywords: ["teacher", "education", "professor"] },
  { emoji: "👨‍🏫", keywords: ["teacher", "man", "professor"] },
  { emoji: "👩‍🏫", keywords: ["teacher", "woman", "professor"] },
  { emoji: "🧑‍🍳", keywords: ["chef", "cook", "food"] },
  { emoji: "👨‍🍳", keywords: ["chef", "man", "cook"] },
  { emoji: "👩‍🍳", keywords: ["chef", "woman", "cook"] },
  { emoji: "🧑‍🎨", keywords: ["artist", "paint", "creative"] },
  { emoji: "👨‍🎨", keywords: ["artist", "man", "paint"] },
  { emoji: "👩‍🎨", keywords: ["artist", "woman", "paint"] },
  { emoji: "🧑‍💻", keywords: ["technologist", "computer", "developer", "programmer"] },
  { emoji: "👨‍💻", keywords: ["technologist", "man", "computer"] },
  { emoji: "👩‍💻", keywords: ["technologist", "woman", "computer"] },
  { emoji: "🧑‍🔬", keywords: ["scientist", "research", "lab"] },
  { emoji: "👨‍🔬", keywords: ["scientist", "man", "research"] },
  { emoji: "👩‍🔬", keywords: ["scientist", "woman", "research"] },
  { emoji: "🧑‍🚀", keywords: ["astronaut", "space", "rocket"] },
  { emoji: "👨‍🚀", keywords: ["astronaut", "man", "space"] },
  { emoji: "👩‍🚀", keywords: ["astronaut", "woman", "space"] },
  { emoji: "🧑‍🚒", keywords: ["firefighter", "fire", "rescue"] },
  { emoji: "👨‍🚒", keywords: ["firefighter", "man", "fire"] },
  { emoji: "👩‍🚒", keywords: ["firefighter", "woman", "fire"] },
  { emoji: "👮", keywords: ["police", "officer", "cop"] },
  { emoji: "🦸", keywords: ["superhero", "hero", "power"] },
  { emoji: "🦹", keywords: ["supervillain", "villain", "evil"] },
  { emoji: "🧙", keywords: ["mage", "wizard", "magic"] },
  { emoji: "🧚", keywords: ["fairy", "magic", "fantasy"] },
  { emoji: "🧛", keywords: ["vampire", "dracula", "halloween"] },
  { emoji: "🧜", keywords: ["merperson", "mermaid", "ocean"] },
  { emoji: "🧝", keywords: ["elf", "fantasy", "magic"] },
  { emoji: "🧞", keywords: ["genie", "magic", "wish"] },
  { emoji: "🧟", keywords: ["zombie", "undead", "halloween"] },
  { emoji: "👻", keywords: ["ghost", "halloween", "spooky"] },
  { emoji: "💀", keywords: ["skull", "death", "skeleton"] },
  { emoji: "☠️", keywords: ["skull", "crossbones", "danger"] },
  { emoji: "👽", keywords: ["alien", "space", "ufo"] },
  { emoji: "👾", keywords: ["alien", "monster", "game"] },
  { emoji: "🤖", keywords: ["robot", "machine", "android"] },
  { emoji: "🎃", keywords: ["pumpkin", "halloween", "jack-o-lantern"] },
  { emoji: "😈", keywords: ["devil", "smile", "purple"] },
  { emoji: "👿", keywords: ["devil", "angry", "imp"] },
  { emoji: "👹", keywords: ["ogre", "monster", "red"] },
  { emoji: "👺", keywords: ["goblin", "monster", "red"] },
  { emoji: "💩", keywords: ["poop", "poo", "pile"] },
  { emoji: "🤡", keywords: ["clown", "face", "circus"] },
  { emoji: "🛡️", keywords: ["shield", "protect", "defense"] },
  { emoji: "⚔️", keywords: ["sword", "crossed", "battle"] },
  { emoji: "🗡️", keywords: ["dagger", "knife", "weapon"] },
  { emoji: "🏹", keywords: ["bow", "arrow", "archery"] },
  { emoji: "🔮", keywords: ["crystal", "ball", "fortune", "magic"] },
  { emoji: "💎", keywords: ["gem", "diamond", "jewel", "precious"] },
  { emoji: "👑", keywords: ["crown", "king", "queen", "royal"] },
  { emoji: "💍", keywords: ["ring", "wedding", "engaged", "diamond"] },
  { emoji: "👓", keywords: ["glasses", "eyeglasses", "spectacles"] },
  { emoji: "🕶️", keywords: ["sunglasses", "cool", "shades"] },
  { emoji: "🎒", keywords: ["backpack", "bag", "school"] },
  { emoji: "👜", keywords: ["handbag", "purse", "bag"] },
  { emoji: "👛", keywords: ["purse", "wallet", "money"] },
  { emoji: "👝", keywords: ["pouch", "bag", "clutch"] },
  { emoji: "🧳", keywords: ["luggage", "suitcase", "travel"] },
  { emoji: "🌂", keywords: ["umbrella", "closed", "rain"] },
  { emoji: "☂️", keywords: ["umbrella", "rain", "weather"] },
  { emoji: "🎀", keywords: ["ribbon", "bow", "gift", "pink"] },
  { emoji: "🧸", keywords: ["teddy", "bear", "toy", "stuffed"] },
  { emoji: "🪀", keywords: ["yo-yo", "toy", "play"] },
  { emoji: "🪁", keywords: ["kite", "fly", "wind"] },
  { emoji: "🛸", keywords: ["ufo", "flying", "saucer", "alien"] },
  { emoji: "🚨", keywords: ["siren", "police", "emergency", "light"] },
  { emoji: "🔆", keywords: ["bright", "sun", "high", "brightness"] },
  { emoji: "🔅", keywords: ["dim", "low", "brightness"] },
];

interface EmojiPickerProps {
  value: string | null | undefined;
  onChange: (emoji: string | null) => void;
  placeholder?: string;
  title?: string;
}

export function EmojiPicker({ value, onChange, placeholder = "Select emoji", title }: EmojiPickerProps) {
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");

  const filteredEmojis = useMemo(() => {
    if (!search.trim()) {
      return EMOJI_DATA.slice(0, 50); // Show first 50 when no search
    }
    const searchLower = search.toLowerCase();
    return EMOJI_DATA.filter(
      (item) =>
        item.keywords.some((keyword) => keyword.includes(searchLower)) ||
        item.emoji.includes(search)
    );
  }, [search]);

  const handleSelect = (emoji: string) => {
    onChange(emoji);
    setOpen(false);
    setSearch("");
  };

  const handleClear = (e: React.MouseEvent) => {
    e.stopPropagation();
    onChange(null);
  };

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          className="w-full justify-between text-lg h-10"
          title={title}
        >
          {value ? (
            <span className="flex items-center gap-2">
              <span>{value}</span>
              <X
                className="h-3 w-3 text-muted-foreground hover:text-foreground"
                onClick={handleClear}
              />
            </span>
          ) : (
            <span className="text-muted-foreground text-sm">{placeholder}</span>
          )}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-72 p-2 z-50" align="start">
        <Input
          placeholder="Search emojis (e.g., home, star, heart)..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="mb-2"
          autoFocus
        />
        <ScrollArea className="h-48">
          {filteredEmojis.length > 0 ? (
            <div className="grid grid-cols-6 gap-1">
              {filteredEmojis.map((item, index) => (
                <Button
                  key={`${item.emoji}-${index}`}
                  variant="ghost"
                  className="h-9 w-9 p-0 text-xl hover:bg-accent"
                  onClick={() => handleSelect(item.emoji)}
                  title={item.keywords.join(", ")}
                >
                  {item.emoji}
                </Button>
              ))}
            </div>
          ) : (
            <div className="text-center text-muted-foreground text-sm py-4">
              No emojis found for "{search}"
            </div>
          )}
        </ScrollArea>
      </PopoverContent>
    </Popover>
  );
}
