import * as React from "react";
import { useState, useMemo } from "react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { X } from "lucide-react";

const EMOJI_DATA = [
  // Smileys & Emotion
  { emoji: "😀", keywords: ["smile", "happy", "face", "grin"] },
  { emoji: "😃", keywords: ["smile", "happy", "face"] },
  { emoji: "😄", keywords: ["smile", "happy", "laugh"] },
  { emoji: "😁", keywords: ["smile", "grin", "happy"] },
  { emoji: "😆", keywords: ["laugh", "happy", "xd"] },
  { emoji: "😅", keywords: ["sweat", "smile", "nervous"] },
  { emoji: "🤣", keywords: ["rofl", "laugh", "rolling"] },
  { emoji: "😂", keywords: ["joy", "laugh", "tears", "lol"] },
  { emoji: "🙂", keywords: ["smile", "slight", "okay"] },
  { emoji: "🙃", keywords: ["upside", "down", "silly"] },
  { emoji: "😉", keywords: ["wink", "flirt"] },
  { emoji: "😊", keywords: ["smile", "blush", "happy", "warm"] },
  { emoji: "😇", keywords: ["angel", "halo", "innocent", "blessed", "holy"] },
  { emoji: "🥰", keywords: ["love", "heart", "happy", "adore"] },
  { emoji: "😍", keywords: ["love", "heart", "eyes", "adore"] },
  { emoji: "🤩", keywords: ["star", "eyes", "excited", "wow"] },
  { emoji: "😘", keywords: ["kiss", "love", "blow"] },
  { emoji: "😗", keywords: ["kiss", "lips"] },
  { emoji: "☺️", keywords: ["smile", "blush", "happy"] },
  { emoji: "😚", keywords: ["kiss", "blush", "love"] },
  { emoji: "😙", keywords: ["kiss", "smile"] },
  { emoji: "🥲", keywords: ["smile", "tear", "happy", "sad"] },
  { emoji: "😋", keywords: ["yummy", "delicious", "tongue"] },
  { emoji: "😛", keywords: ["tongue", "playful", "silly"] },
  { emoji: "😜", keywords: ["wink", "tongue", "crazy"] },
  { emoji: "🤪", keywords: ["zany", "crazy", "wild"] },
  { emoji: "😝", keywords: ["tongue", "squint", "playful"] },
  { emoji: "🤑", keywords: ["money", "rich", "dollar"] },
  { emoji: "🤗", keywords: ["hug", "happy", "warm"] },
  { emoji: "🤭", keywords: ["giggle", "shy", "cover"] },
  { emoji: "🤫", keywords: ["shush", "quiet", "secret"] },
  { emoji: "🤔", keywords: ["think", "hmm", "wonder", "question"] },
  { emoji: "🤐", keywords: ["zip", "mouth", "quiet"] },
  { emoji: "🤨", keywords: ["raised", "eyebrow", "skeptical"] },
  { emoji: "😐", keywords: ["neutral", "blank", "meh"] },
  { emoji: "😑", keywords: ["expressionless", "blank"] },
  { emoji: "😶", keywords: ["silent", "speechless", "quiet"] },
  { emoji: "😏", keywords: ["smirk", "sly", "suggestive"] },
  { emoji: "😒", keywords: ["unamused", "annoyed", "meh"] },
  { emoji: "🙄", keywords: ["eye", "roll", "whatever"] },
  { emoji: "😬", keywords: ["grimace", "awkward", "teeth"] },
  { emoji: "🤥", keywords: ["lie", "pinocchio", "nose"] },
  { emoji: "😌", keywords: ["relieved", "peaceful", "calm"] },
  { emoji: "😔", keywords: ["sad", "pensive", "down"] },
  { emoji: "😪", keywords: ["sleepy", "tired", "tear"] },
  { emoji: "🤤", keywords: ["drool", "want", "hungry"] },
  { emoji: "😴", keywords: ["sleep", "zzz", "tired"] },
  { emoji: "😷", keywords: ["mask", "sick", "medical"] },
  { emoji: "🤒", keywords: ["sick", "thermometer", "fever"] },
  { emoji: "🤕", keywords: ["hurt", "bandage", "injured"] },
  { emoji: "🤢", keywords: ["nauseated", "sick", "green"] },
  { emoji: "🤮", keywords: ["vomit", "sick", "puke"] },
  { emoji: "🤧", keywords: ["sneeze", "sick", "tissue"] },
  { emoji: "🥵", keywords: ["hot", "sweating", "heat"] },
  { emoji: "🥶", keywords: ["cold", "freezing", "ice"] },
  { emoji: "🥴", keywords: ["woozy", "drunk", "dizzy"] },
  { emoji: "😵", keywords: ["dizzy", "dead", "knocked"] },
  { emoji: "🤯", keywords: ["exploding", "mind", "blown", "shocked"] },
  { emoji: "🤠", keywords: ["cowboy", "hat", "western"] },
  { emoji: "🥳", keywords: ["party", "celebrate", "birthday"] },
  { emoji: "🥸", keywords: ["disguise", "glasses", "incognito"] },
  { emoji: "😎", keywords: ["cool", "sunglasses", "awesome"] },
  { emoji: "🤓", keywords: ["nerd", "glasses", "geek"] },
  { emoji: "🧐", keywords: ["monocle", "fancy", "inspect"] },
  { emoji: "😕", keywords: ["confused", "puzzled"] },
  { emoji: "😟", keywords: ["worried", "concerned"] },
  { emoji: "🙁", keywords: ["frown", "sad", "unhappy"] },
  { emoji: "☹️", keywords: ["frown", "sad"] },
  { emoji: "😮", keywords: ["open", "mouth", "surprised"] },
  { emoji: "😯", keywords: ["hushed", "surprised"] },
  { emoji: "😲", keywords: ["astonished", "shocked", "wow"] },
  { emoji: "😳", keywords: ["flushed", "embarrassed", "red"] },
  { emoji: "🥺", keywords: ["pleading", "puppy", "eyes", "please"] },
  { emoji: "😦", keywords: ["frown", "open", "mouth"] },
  { emoji: "😧", keywords: ["anguished", "stressed"] },
  { emoji: "😨", keywords: ["fearful", "scared", "afraid"] },
  { emoji: "😰", keywords: ["anxious", "sweat", "worried"] },
  { emoji: "😥", keywords: ["sad", "relieved", "sweat"] },
  { emoji: "😢", keywords: ["cry", "sad", "tear"] },
  { emoji: "😭", keywords: ["sob", "cry", "sad", "tears"] },
  { emoji: "😱", keywords: ["scream", "fear", "shocked"] },
  { emoji: "😖", keywords: ["confounded", "frustrated"] },
  { emoji: "😣", keywords: ["persevere", "struggling"] },
  { emoji: "😞", keywords: ["disappointed", "sad"] },
  { emoji: "😓", keywords: ["sweat", "downcast", "sad"] },
  { emoji: "😩", keywords: ["weary", "tired", "frustrated"] },
  { emoji: "😫", keywords: ["tired", "exhausted"] },
  { emoji: "🥱", keywords: ["yawn", "tired", "bored"] },
  { emoji: "😤", keywords: ["triumph", "huffing", "angry"] },
  { emoji: "😡", keywords: ["angry", "mad", "rage"] },
  { emoji: "😠", keywords: ["angry", "mad", "grumpy"] },
  { emoji: "🤬", keywords: ["swear", "cursing", "angry"] },
  { emoji: "😈", keywords: ["devil", "evil", "mischief"] },
  { emoji: "👿", keywords: ["devil", "angry", "imp"] },
  { emoji: "💀", keywords: ["skull", "dead", "death"] },
  { emoji: "☠️", keywords: ["skull", "crossbones", "death", "danger"] },
  { emoji: "💩", keywords: ["poop", "poo", "pile"] },
  { emoji: "🤡", keywords: ["clown", "face", "funny"] },
  { emoji: "👹", keywords: ["ogre", "monster", "demon"] },
  { emoji: "👺", keywords: ["goblin", "tengu", "japanese"] },
  { emoji: "👻", keywords: ["ghost", "halloween", "boo"] },
  { emoji: "👽", keywords: ["alien", "ufo", "space"] },
  { emoji: "👾", keywords: ["alien", "monster", "game"] },
  { emoji: "🤖", keywords: ["robot", "bot", "machine"] },
  { emoji: "😺", keywords: ["cat", "smile", "happy"] },
  { emoji: "😸", keywords: ["cat", "grin", "happy"] },
  { emoji: "😹", keywords: ["cat", "joy", "tears"] },
  { emoji: "😻", keywords: ["cat", "love", "heart"] },
  { emoji: "😼", keywords: ["cat", "smirk", "wry"] },
  { emoji: "😽", keywords: ["cat", "kiss"] },
  { emoji: "🙀", keywords: ["cat", "weary", "shocked"] },
  { emoji: "😿", keywords: ["cat", "cry", "sad"] },
  { emoji: "😾", keywords: ["cat", "pout", "angry"] },
  { emoji: "🙈", keywords: ["monkey", "see", "no", "evil"] },
  { emoji: "🙉", keywords: ["monkey", "hear", "no", "evil"] },
  { emoji: "🙊", keywords: ["monkey", "speak", "no", "evil"] },
  { emoji: "💋", keywords: ["kiss", "lips", "love"] },
  { emoji: "💌", keywords: ["love", "letter", "heart"] },
  { emoji: "💘", keywords: ["heart", "arrow", "cupid"] },
  { emoji: "💝", keywords: ["heart", "gift", "love"] },
  { emoji: "💖", keywords: ["heart", "love", "sparkle"] },
  { emoji: "💗", keywords: ["heart", "growing", "love"] },
  { emoji: "💓", keywords: ["heart", "beating", "love"] },
  { emoji: "💞", keywords: ["hearts", "revolving", "love"] },
  { emoji: "💕", keywords: ["hearts", "two", "love"] },
  { emoji: "💟", keywords: ["heart", "decoration", "love"] },
  { emoji: "❣️", keywords: ["heart", "exclamation", "love"] },
  { emoji: "💔", keywords: ["broken", "heart", "sad"] },
  { emoji: "❤️‍🔥", keywords: ["heart", "fire", "passion"] },
  { emoji: "❤️‍🩹", keywords: ["heart", "mending", "heal"] },
  { emoji: "❤️", keywords: ["heart", "love", "like", "favorite"] },
  { emoji: "🧡", keywords: ["heart", "orange", "love"] },
  { emoji: "💛", keywords: ["heart", "yellow", "love"] },
  { emoji: "💚", keywords: ["heart", "green", "love"] },
  { emoji: "💙", keywords: ["heart", "blue", "love"] },
  { emoji: "💜", keywords: ["heart", "purple", "love"] },
  { emoji: "🤎", keywords: ["heart", "brown", "love"] },
  { emoji: "🖤", keywords: ["heart", "black", "love"] },
  { emoji: "🤍", keywords: ["heart", "white", "love"] },
  { emoji: "💯", keywords: ["hundred", "perfect", "score", "100"] },
  { emoji: "💢", keywords: ["anger", "symbol", "mad"] },
  { emoji: "💥", keywords: ["boom", "collision", "explosion"] },
  { emoji: "💫", keywords: ["star", "dizzy", "sparkle"] },
  { emoji: "💦", keywords: ["sweat", "drops", "water"] },
  { emoji: "💨", keywords: ["dash", "wind", "fast"] },
  { emoji: "🕳️", keywords: ["hole", "dark"] },
  { emoji: "💣", keywords: ["bomb", "explosion"] },
  { emoji: "💬", keywords: ["speech", "bubble", "talk", "chat", "message"] },
  { emoji: "👁️‍🗨️", keywords: ["eye", "speech", "witness"] },
  { emoji: "🗨️", keywords: ["speech", "bubble", "left"] },
  { emoji: "🗯️", keywords: ["anger", "bubble", "mad"] },
  { emoji: "💭", keywords: ["thought", "bubble", "think"] },
  { emoji: "💤", keywords: ["sleep", "zzz", "snore"] },
  
  // Gestures & Body
  { emoji: "👋", keywords: ["wave", "hello", "hi", "bye", "hand"] },
  { emoji: "🤚", keywords: ["raised", "back", "hand"] },
  { emoji: "🖐️", keywords: ["hand", "five", "fingers"] },
  { emoji: "✋", keywords: ["hand", "stop", "high five"] },
  { emoji: "🖖", keywords: ["vulcan", "spock", "star trek"] },
  { emoji: "👌", keywords: ["ok", "perfect", "good"] },
  { emoji: "🤌", keywords: ["pinched", "fingers", "italian"] },
  { emoji: "🤏", keywords: ["pinch", "small", "little"] },
  { emoji: "✌️", keywords: ["peace", "victory", "two"] },
  { emoji: "🤞", keywords: ["crossed", "fingers", "luck"] },
  { emoji: "🤟", keywords: ["love", "you", "hand"] },
  { emoji: "🤘", keywords: ["rock", "metal", "horns"] },
  { emoji: "🤙", keywords: ["call", "me", "shaka"] },
  { emoji: "👈", keywords: ["point", "left", "finger"] },
  { emoji: "👉", keywords: ["point", "right", "finger"] },
  { emoji: "👆", keywords: ["point", "up", "finger"] },
  { emoji: "🖕", keywords: ["middle", "finger"] },
  { emoji: "👇", keywords: ["point", "down", "finger"] },
  { emoji: "☝️", keywords: ["point", "up", "one"] },
  { emoji: "👍", keywords: ["thumbs", "up", "good", "like", "yes"] },
  { emoji: "👎", keywords: ["thumbs", "down", "bad", "dislike", "no"] },
  { emoji: "✊", keywords: ["fist", "punch", "power"] },
  { emoji: "👊", keywords: ["fist", "bump", "punch"] },
  { emoji: "🤛", keywords: ["fist", "left"] },
  { emoji: "🤜", keywords: ["fist", "right"] },
  { emoji: "👏", keywords: ["clap", "applause", "bravo"] },
  { emoji: "🙌", keywords: ["hands", "celebration", "hooray"] },
  { emoji: "👐", keywords: ["open", "hands", "jazz"] },
  { emoji: "🤲", keywords: ["palms", "up", "together"] },
  { emoji: "🤝", keywords: ["handshake", "deal", "agree", "partner"] },
  { emoji: "🙏", keywords: ["pray", "prayer", "hands", "please", "thank you", "folded", "namaste", "hope", "faith", "grateful", "bless", "amen"] },
  { emoji: "✍️", keywords: ["write", "writing", "hand"] },
  { emoji: "💅", keywords: ["nail", "polish", "manicure"] },
  { emoji: "🤳", keywords: ["selfie", "phone", "camera"] },
  { emoji: "💪", keywords: ["muscle", "strong", "flex", "bicep"] },
  { emoji: "🦾", keywords: ["mechanical", "arm", "robot"] },
  { emoji: "🦿", keywords: ["mechanical", "leg", "prosthetic"] },
  { emoji: "🦵", keywords: ["leg", "kick"] },
  { emoji: "🦶", keywords: ["foot", "kick"] },
  { emoji: "👂", keywords: ["ear", "listen", "hear"] },
  { emoji: "🦻", keywords: ["ear", "hearing", "aid"] },
  { emoji: "👃", keywords: ["nose", "smell"] },
  { emoji: "🧠", keywords: ["brain", "smart", "think"] },
  { emoji: "🫀", keywords: ["heart", "organ", "anatomical"] },
  { emoji: "🫁", keywords: ["lungs", "breathe"] },
  { emoji: "🦷", keywords: ["tooth", "dental"] },
  { emoji: "🦴", keywords: ["bone", "skeleton"] },
  { emoji: "👀", keywords: ["eyes", "look", "see"] },
  { emoji: "👁️", keywords: ["eye", "look", "see"] },
  { emoji: "👅", keywords: ["tongue", "taste", "lick"] },
  { emoji: "👄", keywords: ["lips", "mouth", "kiss"] },
  
  // People
  { emoji: "👶", keywords: ["baby", "child", "infant"] },
  { emoji: "🧒", keywords: ["child", "kid", "young"] },
  { emoji: "👦", keywords: ["boy", "child", "male"] },
  { emoji: "👧", keywords: ["girl", "child", "female"] },
  { emoji: "🧑", keywords: ["person", "adult"] },
  { emoji: "👱", keywords: ["blond", "person", "hair"] },
  { emoji: "👨", keywords: ["man", "male", "adult"] },
  { emoji: "🧔", keywords: ["beard", "man"] },
  { emoji: "👩", keywords: ["woman", "female", "adult"] },
  { emoji: "🧓", keywords: ["older", "person", "elder"] },
  { emoji: "👴", keywords: ["old", "man", "grandpa"] },
  { emoji: "👵", keywords: ["old", "woman", "grandma"] },
  { emoji: "🙍", keywords: ["frown", "person", "gesture"] },
  { emoji: "🙎", keywords: ["pout", "person", "gesture"] },
  { emoji: "🙅", keywords: ["no", "gesture", "stop"] },
  { emoji: "🙆", keywords: ["ok", "gesture", "person"] },
  { emoji: "💁", keywords: ["information", "help", "person"] },
  { emoji: "🙋", keywords: ["raise", "hand", "person"] },
  { emoji: "🧏", keywords: ["deaf", "person", "hearing"] },
  { emoji: "🙇", keywords: ["bow", "person", "sorry"] },
  { emoji: "🤦", keywords: ["facepalm", "disappointed"] },
  { emoji: "🤷", keywords: ["shrug", "idk", "whatever"] },
  { emoji: "👮", keywords: ["police", "officer", "cop"] },
  { emoji: "🕵️", keywords: ["detective", "spy", "sleuth"] },
  { emoji: "💂", keywords: ["guard", "soldier", "british"] },
  { emoji: "🥷", keywords: ["ninja", "stealth", "hidden"] },
  { emoji: "👷", keywords: ["construction", "worker", "build"] },
  { emoji: "🤴", keywords: ["prince", "royal", "king"] },
  { emoji: "👸", keywords: ["princess", "royal", "queen"] },
  { emoji: "👳", keywords: ["turban", "person"] },
  { emoji: "👲", keywords: ["cap", "person", "chinese"] },
  { emoji: "🧕", keywords: ["hijab", "headscarf", "person"] },
  { emoji: "🤵", keywords: ["tuxedo", "groom", "formal"] },
  { emoji: "👰", keywords: ["bride", "wedding", "veil"] },
  { emoji: "🤰", keywords: ["pregnant", "woman", "baby"] },
  { emoji: "🤱", keywords: ["breastfeeding", "nursing", "baby"] },
  { emoji: "👼", keywords: ["angel", "baby", "cherub", "blessed"] },
  { emoji: "🎅", keywords: ["santa", "christmas", "claus"] },
  { emoji: "🤶", keywords: ["mrs", "claus", "christmas"] },
  { emoji: "🦸", keywords: ["superhero", "hero", "power"] },
  { emoji: "🦹", keywords: ["supervillain", "villain", "evil"] },
  { emoji: "🧙", keywords: ["wizard", "mage", "magic"] },
  { emoji: "🧚", keywords: ["fairy", "magic", "pixie"] },
  { emoji: "🧛", keywords: ["vampire", "dracula"] },
  { emoji: "🧜", keywords: ["merperson", "mermaid", "sea"] },
  { emoji: "🧝", keywords: ["elf", "fantasy", "magical"] },
  { emoji: "🧞", keywords: ["genie", "magic", "lamp"] },
  { emoji: "🧟", keywords: ["zombie", "undead", "walking"] },
  { emoji: "💆", keywords: ["massage", "spa", "relax"] },
  { emoji: "💇", keywords: ["haircut", "salon", "beauty"] },
  { emoji: "🚶", keywords: ["walk", "walking", "person"] },
  { emoji: "🧍", keywords: ["standing", "person"] },
  { emoji: "🧎", keywords: ["kneeling", "person"] },
  { emoji: "🏃", keywords: ["run", "runner", "exercise", "sport"] },
  { emoji: "💃", keywords: ["dance", "dancer", "party"] },
  { emoji: "🕺", keywords: ["dance", "dancer", "party", "disco"] },
  { emoji: "🕴️", keywords: ["levitating", "business", "suit"] },
  { emoji: "👯", keywords: ["bunny", "ears", "dancers"] },
  { emoji: "🧖", keywords: ["sauna", "steam", "spa"] },
  { emoji: "🧗", keywords: ["climb", "climbing", "rock"] },
  { emoji: "🤸", keywords: ["cartwheel", "gymnastics"] },
  { emoji: "🏌️", keywords: ["golf", "golfer", "sport"] },
  { emoji: "🏇", keywords: ["horse", "racing", "jockey"] },
  { emoji: "⛷️", keywords: ["ski", "skiing", "snow"] },
  { emoji: "🏂", keywords: ["snowboard", "snow", "winter"] },
  { emoji: "🏋️", keywords: ["gym", "weight", "exercise", "fitness"] },
  { emoji: "🤼", keywords: ["wrestling", "sport"] },
  { emoji: "🤽", keywords: ["water", "polo", "swim"] },
  { emoji: "🤾", keywords: ["handball", "sport"] },
  { emoji: "🤺", keywords: ["fencing", "sword", "sport"] },
  { emoji: "⛹️", keywords: ["basketball", "bounce", "sport"] },
  { emoji: "🏊", keywords: ["swim", "swimming", "pool"] },
  { emoji: "🚣", keywords: ["row", "boat", "rowing"] },
  { emoji: "🧘", keywords: ["yoga", "meditation", "zen", "calm"] },
  { emoji: "🛀", keywords: ["bath", "bathtub", "relax"] },
  { emoji: "🛌", keywords: ["sleep", "bed", "rest"] },
  { emoji: "👭", keywords: ["women", "holding", "hands"] },
  { emoji: "👫", keywords: ["couple", "holding", "hands"] },
  { emoji: "👬", keywords: ["men", "holding", "hands"] },
  { emoji: "💏", keywords: ["kiss", "couple", "love"] },
  { emoji: "💑", keywords: ["couple", "heart", "love"] },
  { emoji: "👪", keywords: ["family", "parents", "child"] },
  { emoji: "👨‍👩‍👦", keywords: ["family", "man", "woman", "boy"] },
  { emoji: "👨‍👩‍👧", keywords: ["family", "man", "woman", "girl"] },
  { emoji: "👨‍👩‍👧‍👦", keywords: ["family", "man", "woman", "children"] },
  { emoji: "🗣️", keywords: ["speaking", "head", "talk"] },
  { emoji: "👤", keywords: ["silhouette", "person", "user"] },
  { emoji: "👥", keywords: ["silhouettes", "people", "users"] },
  { emoji: "🫂", keywords: ["hug", "people", "embrace"] },
  { emoji: "👣", keywords: ["footprints", "feet", "tracks"] },
  
  // Animals & Nature
  { emoji: "🐵", keywords: ["monkey", "animal", "ape"] },
  { emoji: "🐒", keywords: ["monkey", "animal"] },
  { emoji: "🦍", keywords: ["gorilla", "ape", "animal"] },
  { emoji: "🦧", keywords: ["orangutan", "ape", "animal"] },
  { emoji: "🐶", keywords: ["dog", "puppy", "pet", "animal"] },
  { emoji: "🐕", keywords: ["dog", "pet", "animal"] },
  { emoji: "🦮", keywords: ["guide", "dog", "service"] },
  { emoji: "🐕‍🦺", keywords: ["service", "dog", "vest"] },
  { emoji: "🐩", keywords: ["poodle", "dog", "pet"] },
  { emoji: "🐺", keywords: ["wolf", "animal", "wild"] },
  { emoji: "🦊", keywords: ["fox", "animal", "wild"] },
  { emoji: "🦝", keywords: ["raccoon", "animal", "wild"] },
  { emoji: "🐱", keywords: ["cat", "kitty", "pet", "animal"] },
  { emoji: "🐈", keywords: ["cat", "pet", "animal"] },
  { emoji: "🐈‍⬛", keywords: ["black", "cat", "pet"] },
  { emoji: "🦁", keywords: ["lion", "animal", "wild", "cat"] },
  { emoji: "🐯", keywords: ["tiger", "animal", "wild", "cat"] },
  { emoji: "🐅", keywords: ["tiger", "animal", "wild"] },
  { emoji: "🐆", keywords: ["leopard", "animal", "wild"] },
  { emoji: "🐴", keywords: ["horse", "animal", "face"] },
  { emoji: "🐎", keywords: ["horse", "racing", "animal"] },
  { emoji: "🦄", keywords: ["unicorn", "magic", "fantasy"] },
  { emoji: "🦓", keywords: ["zebra", "animal", "stripes"] },
  { emoji: "🦌", keywords: ["deer", "animal", "nature"] },
  { emoji: "🦬", keywords: ["bison", "buffalo", "animal"] },
  { emoji: "🐮", keywords: ["cow", "animal", "farm"] },
  { emoji: "🐂", keywords: ["ox", "bull", "animal"] },
  { emoji: "🐃", keywords: ["water", "buffalo", "animal"] },
  { emoji: "🐄", keywords: ["cow", "animal", "farm"] },
  { emoji: "🐷", keywords: ["pig", "animal", "farm"] },
  { emoji: "🐖", keywords: ["pig", "animal", "farm"] },
  { emoji: "🐗", keywords: ["boar", "wild", "animal"] },
  { emoji: "🐽", keywords: ["pig", "nose", "snout"] },
  { emoji: "🐏", keywords: ["ram", "sheep", "animal"] },
  { emoji: "🐑", keywords: ["sheep", "animal", "wool"] },
  { emoji: "🐐", keywords: ["goat", "animal", "farm"] },
  { emoji: "🐪", keywords: ["camel", "desert", "animal"] },
  { emoji: "🐫", keywords: ["camel", "two", "humps"] },
  { emoji: "🦙", keywords: ["llama", "alpaca", "animal"] },
  { emoji: "🦒", keywords: ["giraffe", "animal", "tall"] },
  { emoji: "🐘", keywords: ["elephant", "animal", "big"] },
  { emoji: "🦣", keywords: ["mammoth", "prehistoric", "extinct"] },
  { emoji: "🦏", keywords: ["rhino", "rhinoceros", "animal"] },
  { emoji: "🦛", keywords: ["hippo", "hippopotamus", "animal"] },
  { emoji: "🐭", keywords: ["mouse", "animal", "rodent"] },
  { emoji: "🐁", keywords: ["mouse", "animal", "rodent"] },
  { emoji: "🐀", keywords: ["rat", "animal", "rodent"] },
  { emoji: "🐹", keywords: ["hamster", "pet", "animal"] },
  { emoji: "🐰", keywords: ["rabbit", "bunny", "animal"] },
  { emoji: "🐇", keywords: ["rabbit", "bunny", "animal"] },
  { emoji: "🐿️", keywords: ["chipmunk", "squirrel", "animal"] },
  { emoji: "🦫", keywords: ["beaver", "animal", "dam"] },
  { emoji: "🦔", keywords: ["hedgehog", "animal", "spiky"] },
  { emoji: "🦇", keywords: ["bat", "animal", "vampire"] },
  { emoji: "🐻", keywords: ["bear", "animal", "wild"] },
  { emoji: "🐻‍❄️", keywords: ["polar", "bear", "arctic"] },
  { emoji: "🐨", keywords: ["koala", "animal", "australia"] },
  { emoji: "🐼", keywords: ["panda", "bear", "animal"] },
  { emoji: "🦥", keywords: ["sloth", "animal", "lazy"] },
  { emoji: "🦦", keywords: ["otter", "animal", "water"] },
  { emoji: "🦨", keywords: ["skunk", "animal", "smell"] },
  { emoji: "🦘", keywords: ["kangaroo", "animal", "australia"] },
  { emoji: "🦡", keywords: ["badger", "animal", "wild"] },
  { emoji: "🐾", keywords: ["paw", "prints", "animal"] },
  { emoji: "🦃", keywords: ["turkey", "bird", "thanksgiving"] },
  { emoji: "🐔", keywords: ["chicken", "animal", "farm", "bird"] },
  { emoji: "🐓", keywords: ["rooster", "chicken", "bird"] },
  { emoji: "🐣", keywords: ["hatching", "chick", "bird"] },
  { emoji: "🐤", keywords: ["baby", "chick", "bird"] },
  { emoji: "🐥", keywords: ["front", "facing", "chick"] },
  { emoji: "🐦", keywords: ["bird", "animal", "fly"] },
  { emoji: "🐧", keywords: ["penguin", "animal", "bird", "cold"] },
  { emoji: "🕊️", keywords: ["dove", "peace", "bird", "holy", "spirit", "faith"] },
  { emoji: "🦅", keywords: ["eagle", "bird", "america"] },
  { emoji: "🦆", keywords: ["duck", "bird", "animal"] },
  { emoji: "🦢", keywords: ["swan", "bird", "elegant"] },
  { emoji: "🦉", keywords: ["owl", "bird", "wise"] },
  { emoji: "🦤", keywords: ["dodo", "bird", "extinct"] },
  { emoji: "🪶", keywords: ["feather", "bird", "light"] },
  { emoji: "🦩", keywords: ["flamingo", "bird", "pink"] },
  { emoji: "🦚", keywords: ["peacock", "bird", "feathers"] },
  { emoji: "🦜", keywords: ["parrot", "bird", "tropical"] },
  { emoji: "🐸", keywords: ["frog", "animal", "green"] },
  { emoji: "🐊", keywords: ["crocodile", "alligator", "animal"] },
  { emoji: "🐢", keywords: ["turtle", "animal", "slow"] },
  { emoji: "🦎", keywords: ["lizard", "reptile", "animal"] },
  { emoji: "🐍", keywords: ["snake", "reptile", "animal"] },
  { emoji: "🐲", keywords: ["dragon", "face", "fantasy"] },
  { emoji: "🐉", keywords: ["dragon", "fantasy", "mythical"] },
  { emoji: "🦕", keywords: ["dinosaur", "sauropod", "prehistoric"] },
  { emoji: "🦖", keywords: ["trex", "dinosaur", "prehistoric"] },
  { emoji: "🐳", keywords: ["whale", "spouting", "ocean"] },
  { emoji: "🐋", keywords: ["whale", "ocean", "animal"] },
  { emoji: "🐬", keywords: ["dolphin", "ocean", "animal"] },
  { emoji: "🦭", keywords: ["seal", "ocean", "animal"] },
  { emoji: "🐟", keywords: ["fish", "animal", "ocean"] },
  { emoji: "🐠", keywords: ["tropical", "fish", "animal"] },
  { emoji: "🐡", keywords: ["blowfish", "puffer", "fish"] },
  { emoji: "🦈", keywords: ["shark", "fish", "ocean"] },
  { emoji: "🐙", keywords: ["octopus", "ocean", "animal"] },
  { emoji: "🐚", keywords: ["shell", "beach", "ocean"] },
  { emoji: "🐌", keywords: ["snail", "slow", "animal"] },
  { emoji: "🦋", keywords: ["butterfly", "insect", "pretty"] },
  { emoji: "🐛", keywords: ["bug", "insect", "caterpillar"] },
  { emoji: "🐜", keywords: ["ant", "insect", "bug"] },
  { emoji: "🐝", keywords: ["bee", "insect", "honey"] },
  { emoji: "🪲", keywords: ["beetle", "bug", "insect"] },
  { emoji: "🐞", keywords: ["ladybug", "insect", "bug"] },
  { emoji: "🦗", keywords: ["cricket", "insect", "bug"] },
  { emoji: "🪳", keywords: ["cockroach", "bug", "insect"] },
  { emoji: "🕷️", keywords: ["spider", "insect", "web"] },
  { emoji: "🕸️", keywords: ["web", "spider", "cobweb"] },
  { emoji: "🦂", keywords: ["scorpion", "insect", "animal"] },
  { emoji: "🦟", keywords: ["mosquito", "insect", "bug"] },
  { emoji: "🪰", keywords: ["fly", "bug", "insect"] },
  { emoji: "🪱", keywords: ["worm", "bug", "insect"] },
  { emoji: "🦠", keywords: ["microbe", "germ", "virus", "bacteria"] },
  { emoji: "💐", keywords: ["bouquet", "flowers", "gift"] },
  { emoji: "🌸", keywords: ["flower", "blossom", "cherry", "spring"] },
  { emoji: "💮", keywords: ["flower", "white", "symbol"] },
  { emoji: "🏵️", keywords: ["rosette", "flower", "decoration"] },
  { emoji: "🌹", keywords: ["rose", "flower", "red", "love"] },
  { emoji: "🥀", keywords: ["wilted", "flower", "sad"] },
  { emoji: "🌺", keywords: ["flower", "hibiscus", "tropical"] },
  { emoji: "🌻", keywords: ["flower", "sunflower", "yellow"] },
  { emoji: "🌼", keywords: ["flower", "blossom", "daisy"] },
  { emoji: "🌷", keywords: ["tulip", "flower", "spring"] },
  { emoji: "🌱", keywords: ["plant", "seedling", "grow", "garden"] },
  { emoji: "🪴", keywords: ["potted", "plant", "indoor"] },
  { emoji: "🌲", keywords: ["tree", "evergreen", "nature", "forest"] },
  { emoji: "🌳", keywords: ["tree", "nature", "forest", "deciduous"] },
  { emoji: "🌴", keywords: ["palm", "tree", "tropical", "beach"] },
  { emoji: "🌵", keywords: ["cactus", "desert", "plant"] },
  { emoji: "🌾", keywords: ["rice", "ear", "grain"] },
  { emoji: "🌿", keywords: ["herb", "plant", "green"] },
  { emoji: "☘️", keywords: ["shamrock", "clover", "irish"] },
  { emoji: "🍀", keywords: ["clover", "luck", "lucky", "four leaf"] },
  { emoji: "🍁", keywords: ["leaf", "maple", "fall", "autumn"] },
  { emoji: "🍂", keywords: ["leaves", "fall", "autumn"] },
  { emoji: "🍃", keywords: ["leaf", "wind", "nature"] },
  
  // Food & Drink
  { emoji: "🍇", keywords: ["grapes", "fruit", "wine"] },
  { emoji: "🍈", keywords: ["melon", "fruit"] },
  { emoji: "🍉", keywords: ["watermelon", "fruit", "summer"] },
  { emoji: "🍊", keywords: ["orange", "fruit", "citrus"] },
  { emoji: "🍋", keywords: ["lemon", "fruit", "citrus"] },
  { emoji: "🍌", keywords: ["banana", "fruit", "yellow"] },
  { emoji: "🍍", keywords: ["pineapple", "fruit", "tropical"] },
  { emoji: "🥭", keywords: ["mango", "fruit", "tropical"] },
  { emoji: "🍎", keywords: ["apple", "fruit", "red"] },
  { emoji: "🍏", keywords: ["apple", "fruit", "green"] },
  { emoji: "🍐", keywords: ["pear", "fruit"] },
  { emoji: "🍑", keywords: ["peach", "fruit"] },
  { emoji: "🍒", keywords: ["cherries", "fruit", "red"] },
  { emoji: "🍓", keywords: ["strawberry", "fruit", "berry"] },
  { emoji: "🫐", keywords: ["blueberries", "fruit", "berry"] },
  { emoji: "🥝", keywords: ["kiwi", "fruit", "green"] },
  { emoji: "🍅", keywords: ["tomato", "vegetable", "red"] },
  { emoji: "🫒", keywords: ["olive", "fruit", "oil"] },
  { emoji: "🥥", keywords: ["coconut", "tropical", "fruit"] },
  { emoji: "🥑", keywords: ["avocado", "fruit", "green"] },
  { emoji: "🍆", keywords: ["eggplant", "vegetable", "aubergine"] },
  { emoji: "🥔", keywords: ["potato", "vegetable", "tuber"] },
  { emoji: "🥕", keywords: ["carrot", "vegetable", "orange"] },
  { emoji: "🌽", keywords: ["corn", "vegetable", "maize"] },
  { emoji: "🌶️", keywords: ["pepper", "hot", "spicy", "chili"] },
  { emoji: "🫑", keywords: ["bell", "pepper", "vegetable"] },
  { emoji: "🥒", keywords: ["cucumber", "vegetable", "pickle"] },
  { emoji: "🥬", keywords: ["leafy", "green", "vegetable"] },
  { emoji: "🥦", keywords: ["broccoli", "vegetable", "green"] },
  { emoji: "🧄", keywords: ["garlic", "vegetable", "flavor"] },
  { emoji: "🧅", keywords: ["onion", "vegetable", "flavor"] },
  { emoji: "🍄", keywords: ["mushroom", "vegetable", "fungus"] },
  { emoji: "🥜", keywords: ["peanuts", "nuts", "snack"] },
  { emoji: "🌰", keywords: ["chestnut", "nut", "fall"] },
  { emoji: "🍞", keywords: ["bread", "loaf", "food"] },
  { emoji: "🥐", keywords: ["croissant", "bread", "french"] },
  { emoji: "🥖", keywords: ["baguette", "bread", "french"] },
  { emoji: "🫓", keywords: ["flatbread", "pita", "bread"] },
  { emoji: "🥨", keywords: ["pretzel", "snack", "german"] },
  { emoji: "🥯", keywords: ["bagel", "bread", "breakfast"] },
  { emoji: "🥞", keywords: ["pancakes", "breakfast", "food"] },
  { emoji: "🧇", keywords: ["waffle", "breakfast", "food"] },
  { emoji: "🧀", keywords: ["cheese", "dairy", "food"] },
  { emoji: "🍖", keywords: ["meat", "bone", "food"] },
  { emoji: "🍗", keywords: ["chicken", "leg", "poultry"] },
  { emoji: "🥩", keywords: ["steak", "meat", "beef"] },
  { emoji: "🥓", keywords: ["bacon", "meat", "breakfast"] },
  { emoji: "🍔", keywords: ["burger", "hamburger", "food"] },
  { emoji: "🍟", keywords: ["fries", "french", "food"] },
  { emoji: "🍕", keywords: ["pizza", "food", "slice"] },
  { emoji: "🌭", keywords: ["hotdog", "food", "sausage"] },
  { emoji: "🥪", keywords: ["sandwich", "food", "lunch"] },
  { emoji: "🌮", keywords: ["taco", "food", "mexican"] },
  { emoji: "🌯", keywords: ["burrito", "food", "wrap"] },
  { emoji: "🫔", keywords: ["tamale", "food", "mexican"] },
  { emoji: "🥙", keywords: ["pita", "falafel", "food"] },
  { emoji: "🧆", keywords: ["falafel", "food", "middle eastern"] },
  { emoji: "🥚", keywords: ["egg", "food", "breakfast"] },
  { emoji: "🍳", keywords: ["fried", "egg", "cooking", "pan"] },
  { emoji: "🥘", keywords: ["pan", "food", "cooking"] },
  { emoji: "🍲", keywords: ["pot", "food", "stew"] },
  { emoji: "🫕", keywords: ["fondue", "cheese", "food"] },
  { emoji: "🥣", keywords: ["bowl", "spoon", "cereal"] },
  { emoji: "🥗", keywords: ["salad", "healthy", "food", "green"] },
  { emoji: "🍿", keywords: ["popcorn", "movie", "snack"] },
  { emoji: "🧈", keywords: ["butter", "dairy", "food"] },
  { emoji: "🧂", keywords: ["salt", "seasoning", "food"] },
  { emoji: "🥫", keywords: ["can", "canned", "food"] },
  { emoji: "🍱", keywords: ["bento", "box", "japanese"] },
  { emoji: "🍘", keywords: ["rice", "cracker", "japanese"] },
  { emoji: "🍙", keywords: ["rice", "ball", "onigiri"] },
  { emoji: "🍚", keywords: ["rice", "cooked", "food"] },
  { emoji: "🍛", keywords: ["curry", "rice", "food"] },
  { emoji: "🍜", keywords: ["noodles", "ramen", "food", "asian"] },
  { emoji: "🍝", keywords: ["pasta", "spaghetti", "food", "italian"] },
  { emoji: "🍠", keywords: ["sweet", "potato", "food"] },
  { emoji: "🍢", keywords: ["oden", "skewer", "japanese"] },
  { emoji: "🍣", keywords: ["sushi", "food", "japanese", "fish"] },
  { emoji: "🍤", keywords: ["shrimp", "fried", "tempura"] },
  { emoji: "🍥", keywords: ["fish", "cake", "narutomaki"] },
  { emoji: "🥮", keywords: ["moon", "cake", "chinese"] },
  { emoji: "🍡", keywords: ["dango", "sweet", "japanese"] },
  { emoji: "🥟", keywords: ["dumpling", "gyoza", "food"] },
  { emoji: "🥠", keywords: ["fortune", "cookie", "chinese"] },
  { emoji: "🥡", keywords: ["takeout", "box", "chinese"] },
  { emoji: "🦀", keywords: ["crab", "seafood", "animal"] },
  { emoji: "🦞", keywords: ["lobster", "seafood", "animal"] },
  { emoji: "🦐", keywords: ["shrimp", "seafood", "animal"] },
  { emoji: "🦑", keywords: ["squid", "seafood", "animal"] },
  { emoji: "🦪", keywords: ["oyster", "seafood", "pearl"] },
  { emoji: "🍦", keywords: ["ice cream", "dessert", "sweet", "cold"] },
  { emoji: "🍧", keywords: ["shaved", "ice", "dessert"] },
  { emoji: "🍨", keywords: ["ice", "cream", "dessert"] },
  { emoji: "🍩", keywords: ["donut", "doughnut", "dessert", "sweet"] },
  { emoji: "🍪", keywords: ["cookie", "dessert", "sweet", "biscuit"] },
  { emoji: "🎂", keywords: ["cake", "birthday", "celebration"] },
  { emoji: "🍰", keywords: ["cake", "dessert", "sweet"] },
  { emoji: "🧁", keywords: ["cupcake", "dessert", "sweet"] },
  { emoji: "🥧", keywords: ["pie", "dessert", "baked"] },
  { emoji: "🍫", keywords: ["chocolate", "candy", "sweet"] },
  { emoji: "🍬", keywords: ["candy", "sweet", "sugar"] },
  { emoji: "🍭", keywords: ["lollipop", "candy", "sweet"] },
  { emoji: "🍮", keywords: ["custard", "pudding", "dessert"] },
  { emoji: "🍯", keywords: ["honey", "pot", "sweet"] },
  { emoji: "🍼", keywords: ["bottle", "baby", "milk"] },
  { emoji: "🥛", keywords: ["milk", "glass", "drink"] },
  { emoji: "☕", keywords: ["coffee", "drink", "hot", "cafe", "cup"] },
  { emoji: "🫖", keywords: ["teapot", "tea", "drink"] },
  { emoji: "🍵", keywords: ["tea", "drink", "hot", "cup"] },
  { emoji: "🍶", keywords: ["sake", "drink", "japanese"] },
  { emoji: "🍾", keywords: ["champagne", "bottle", "celebration"] },
  { emoji: "🍷", keywords: ["wine", "drink", "alcohol", "glass"] },
  { emoji: "🍸", keywords: ["cocktail", "drink", "alcohol"] },
  { emoji: "🍹", keywords: ["tropical", "drink", "cocktail"] },
  { emoji: "🍺", keywords: ["beer", "drink", "alcohol", "mug"] },
  { emoji: "🍻", keywords: ["beers", "cheers", "alcohol"] },
  { emoji: "🥂", keywords: ["cheers", "glasses", "toast"] },
  { emoji: "🥃", keywords: ["whiskey", "tumbler", "drink"] },
  { emoji: "🥤", keywords: ["drink", "soda", "cup", "beverage"] },
  { emoji: "🧋", keywords: ["bubble", "tea", "boba"] },
  { emoji: "🧃", keywords: ["juice", "box", "drink"] },
  { emoji: "🧉", keywords: ["mate", "drink", "tea"] },
  { emoji: "🧊", keywords: ["ice", "cube", "cold"] },
  { emoji: "🥢", keywords: ["chopsticks", "utensils", "asian"] },
  { emoji: "🍽️", keywords: ["plate", "cutlery", "dining"] },
  { emoji: "🍴", keywords: ["fork", "knife", "utensils"] },
  { emoji: "🥄", keywords: ["spoon", "utensil", "eat"] },
  { emoji: "🔪", keywords: ["knife", "kitchen", "cut"] },
  { emoji: "🏺", keywords: ["amphora", "jar", "vase"] },
  
  // Activities & Sports
  { emoji: "🎃", keywords: ["pumpkin", "halloween", "jack o lantern"] },
  { emoji: "🎄", keywords: ["christmas", "tree", "holiday"] },
  { emoji: "🎆", keywords: ["fireworks", "celebration", "new year"] },
  { emoji: "🎇", keywords: ["sparkler", "fireworks", "celebration"] },
  { emoji: "🧨", keywords: ["firecracker", "celebration", "explosive"] },
  { emoji: "✨", keywords: ["sparkle", "shine", "magic", "special"] },
  { emoji: "🎈", keywords: ["balloon", "party", "celebration"] },
  { emoji: "🎉", keywords: ["party", "celebration", "confetti", "tada"] },
  { emoji: "🎊", keywords: ["confetti", "celebration", "party"] },
  { emoji: "🎋", keywords: ["tanabata", "tree", "japanese"] },
  { emoji: "🎍", keywords: ["bamboo", "decoration", "japanese"] },
  { emoji: "🎎", keywords: ["dolls", "japanese", "festival"] },
  { emoji: "🎏", keywords: ["carp", "streamer", "japanese"] },
  { emoji: "🎐", keywords: ["wind", "chime", "japanese"] },
  { emoji: "🎑", keywords: ["moon", "ceremony", "japanese"] },
  { emoji: "🧧", keywords: ["red", "envelope", "chinese"] },
  { emoji: "🎀", keywords: ["ribbon", "gift", "bow"] },
  { emoji: "🎁", keywords: ["gift", "present", "birthday", "surprise"] },
  { emoji: "🎗️", keywords: ["ribbon", "awareness", "reminder"] },
  { emoji: "🎟️", keywords: ["ticket", "admission", "event"] },
  { emoji: "🎫", keywords: ["ticket", "event", "admission"] },
  { emoji: "🎖️", keywords: ["medal", "military", "honor"] },
  { emoji: "🏆", keywords: ["trophy", "winner", "champion"] },
  { emoji: "🏅", keywords: ["medal", "sports", "winner"] },
  { emoji: "🥇", keywords: ["gold", "medal", "first"] },
  { emoji: "🥈", keywords: ["silver", "medal", "second"] },
  { emoji: "🥉", keywords: ["bronze", "medal", "third"] },
  { emoji: "⚽", keywords: ["soccer", "football", "sport", "ball"] },
  { emoji: "⚾", keywords: ["baseball", "sport", "ball"] },
  { emoji: "🥎", keywords: ["softball", "sport", "ball"] },
  { emoji: "🏀", keywords: ["basketball", "sport", "ball"] },
  { emoji: "🏐", keywords: ["volleyball", "sport", "ball"] },
  { emoji: "🏈", keywords: ["football", "sport", "american"] },
  { emoji: "🏉", keywords: ["rugby", "sport", "ball"] },
  { emoji: "🎾", keywords: ["tennis", "sport", "ball"] },
  { emoji: "🥏", keywords: ["frisbee", "disc", "flying"] },
  { emoji: "🎳", keywords: ["bowling", "sport", "pins"] },
  { emoji: "🏏", keywords: ["cricket", "sport", "bat"] },
  { emoji: "🏑", keywords: ["field", "hockey", "sport"] },
  { emoji: "🏒", keywords: ["ice", "hockey", "sport"] },
  { emoji: "🥍", keywords: ["lacrosse", "sport", "stick"] },
  { emoji: "🏓", keywords: ["ping pong", "table tennis", "sport"] },
  { emoji: "🏸", keywords: ["badminton", "sport", "racquet"] },
  { emoji: "🥊", keywords: ["boxing", "glove", "sport"] },
  { emoji: "🥋", keywords: ["martial", "arts", "karate"] },
  { emoji: "🥅", keywords: ["goal", "net", "sport"] },
  { emoji: "⛳", keywords: ["golf", "flag", "sport"] },
  { emoji: "⛸️", keywords: ["ice", "skate", "skating"] },
  { emoji: "🎣", keywords: ["fishing", "pole", "fish"] },
  { emoji: "🤿", keywords: ["diving", "mask", "snorkel"] },
  { emoji: "🎽", keywords: ["running", "shirt", "sport"] },
  { emoji: "🎿", keywords: ["ski", "skiing", "snow"] },
  { emoji: "🛷", keywords: ["sled", "snow", "winter"] },
  { emoji: "🥌", keywords: ["curling", "stone", "sport"] },
  { emoji: "🎯", keywords: ["target", "dart", "bullseye", "goal"] },
  { emoji: "🪀", keywords: ["yo-yo", "toy", "play"] },
  { emoji: "🪁", keywords: ["kite", "fly", "toy"] },
  { emoji: "🎱", keywords: ["pool", "billiard", "8 ball"] },
  { emoji: "🔮", keywords: ["crystal", "ball", "fortune"] },
  { emoji: "🪄", keywords: ["magic", "wand", "wizard"] },
  { emoji: "🧿", keywords: ["evil", "eye", "nazar"] },
  { emoji: "🎮", keywords: ["game", "gaming", "controller", "play"] },
  { emoji: "🕹️", keywords: ["joystick", "game", "arcade"] },
  { emoji: "🎰", keywords: ["slot", "machine", "casino"] },
  { emoji: "🎲", keywords: ["dice", "game", "random", "luck"] },
  { emoji: "🧩", keywords: ["puzzle", "game", "piece"] },
  { emoji: "🧸", keywords: ["teddy", "bear", "toy"] },
  { emoji: "🪆", keywords: ["nesting", "dolls", "russian"] },
  { emoji: "♠️", keywords: ["spade", "card", "poker"] },
  { emoji: "♥️", keywords: ["heart", "card", "poker"] },
  { emoji: "♦️", keywords: ["diamond", "card", "poker"] },
  { emoji: "♣️", keywords: ["club", "card", "poker"] },
  { emoji: "♟️", keywords: ["chess", "game", "strategy"] },
  { emoji: "🃏", keywords: ["joker", "card", "wild"] },
  { emoji: "🀄", keywords: ["mahjong", "game", "tile"] },
  { emoji: "🎴", keywords: ["flower", "playing", "cards"] },
  { emoji: "🎭", keywords: ["theater", "drama", "mask", "arts"] },
  { emoji: "🖼️", keywords: ["frame", "picture", "art"] },
  { emoji: "🎨", keywords: ["art", "paint", "creative", "color"] },
  { emoji: "🧵", keywords: ["thread", "sewing", "string"] },
  { emoji: "🪡", keywords: ["needle", "sewing", "thread"] },
  { emoji: "🧶", keywords: ["yarn", "knit", "ball"] },
  { emoji: "🪢", keywords: ["knot", "rope", "tied"] },
  
  // Travel & Places
  { emoji: "🌍", keywords: ["earth", "globe", "world", "europe", "africa"] },
  { emoji: "🌎", keywords: ["earth", "globe", "world", "americas"] },
  { emoji: "🌏", keywords: ["earth", "globe", "world", "asia"] },
  { emoji: "🌐", keywords: ["globe", "meridians", "internet"] },
  { emoji: "🗺️", keywords: ["map", "world", "travel"] },
  { emoji: "🧭", keywords: ["compass", "direction", "navigate"] },
  { emoji: "🏔️", keywords: ["mountain", "snow", "nature"] },
  { emoji: "⛰️", keywords: ["mountain", "nature", "hike"] },
  { emoji: "🌋", keywords: ["volcano", "mountain", "lava"] },
  { emoji: "🗻", keywords: ["mountain", "fuji", "japan"] },
  { emoji: "🏕️", keywords: ["camp", "camping", "tent", "outdoor"] },
  { emoji: "🏖️", keywords: ["beach", "vacation", "summer", "sand"] },
  { emoji: "🏜️", keywords: ["desert", "sand", "hot"] },
  { emoji: "🏝️", keywords: ["island", "desert", "tropical"] },
  { emoji: "🏞️", keywords: ["park", "national", "nature"] },
  { emoji: "🏟️", keywords: ["stadium", "sports", "arena"] },
  { emoji: "🏛️", keywords: ["museum", "building", "classical"] },
  { emoji: "🏗️", keywords: ["construction", "building", "crane"] },
  { emoji: "🧱", keywords: ["brick", "bricks", "building"] },
  { emoji: "🪨", keywords: ["rock", "stone", "boulder"] },
  { emoji: "🪵", keywords: ["wood", "log", "timber"] },
  { emoji: "🛖", keywords: ["hut", "house", "shelter"] },
  { emoji: "🏠", keywords: ["house", "home", "building"] },
  { emoji: "🏡", keywords: ["home", "house", "garden"] },
  { emoji: "🏢", keywords: ["building", "office", "work"] },
  { emoji: "🏣", keywords: ["post", "office", "japanese"] },
  { emoji: "🏤", keywords: ["post", "office", "european"] },
  { emoji: "🏥", keywords: ["hospital", "health", "medical"] },
  { emoji: "🏦", keywords: ["bank", "money", "building"] },
  { emoji: "🏨", keywords: ["hotel", "building", "accommodation"] },
  { emoji: "🏩", keywords: ["love", "hotel", "romance"] },
  { emoji: "🏪", keywords: ["store", "shop", "convenience"] },
  { emoji: "🏫", keywords: ["school", "education", "building"] },
  { emoji: "🏬", keywords: ["mall", "store", "department"] },
  { emoji: "🏭", keywords: ["factory", "industry", "building"] },
  { emoji: "🏯", keywords: ["castle", "japanese", "building"] },
  { emoji: "🏰", keywords: ["castle", "european", "building"] },
  { emoji: "💒", keywords: ["wedding", "chapel", "church"] },
  { emoji: "🗼", keywords: ["tower", "tokyo", "landmark"] },
  { emoji: "🗽", keywords: ["statue", "liberty", "landmark"] },
  { emoji: "⛪", keywords: ["church", "religion", "building"] },
  { emoji: "🕌", keywords: ["mosque", "religion", "building"] },
  { emoji: "🛕", keywords: ["temple", "hindu", "religion"] },
  { emoji: "🕍", keywords: ["synagogue", "jewish", "religion"] },
  { emoji: "⛩️", keywords: ["shinto", "shrine", "japanese"] },
  { emoji: "🕋", keywords: ["kaaba", "mecca", "islam"] },
  { emoji: "⛲", keywords: ["fountain", "water", "park"] },
  { emoji: "⛺", keywords: ["tent", "camping", "outdoor"] },
  { emoji: "🌁", keywords: ["foggy", "city", "san francisco"] },
  { emoji: "🌃", keywords: ["night", "city", "stars"] },
  { emoji: "🏙️", keywords: ["cityscape", "city", "skyline"] },
  { emoji: "🌄", keywords: ["sunrise", "mountain", "morning"] },
  { emoji: "🌅", keywords: ["sunrise", "beach", "morning"] },
  { emoji: "🌆", keywords: ["cityscape", "dusk", "evening"] },
  { emoji: "🌇", keywords: ["sunset", "city", "evening"] },
  { emoji: "🌉", keywords: ["bridge", "night", "city"] },
  { emoji: "♨️", keywords: ["hot", "springs", "steam"] },
  { emoji: "🎠", keywords: ["carousel", "horse", "amusement"] },
  { emoji: "🎡", keywords: ["ferris", "wheel", "amusement"] },
  { emoji: "🎢", keywords: ["roller", "coaster", "amusement"] },
  { emoji: "💈", keywords: ["barber", "pole", "haircut"] },
  { emoji: "🎪", keywords: ["circus", "tent", "entertainment"] },
  { emoji: "🚂", keywords: ["train", "locomotive", "transport"] },
  { emoji: "🚃", keywords: ["train", "railway", "car"] },
  { emoji: "🚄", keywords: ["train", "bullet", "fast", "rail"] },
  { emoji: "🚅", keywords: ["train", "bullet", "shinkansen"] },
  { emoji: "🚆", keywords: ["train", "transport", "rail"] },
  { emoji: "🚇", keywords: ["metro", "subway", "underground"] },
  { emoji: "🚈", keywords: ["light", "rail", "train"] },
  { emoji: "🚉", keywords: ["station", "train", "transport"] },
  { emoji: "🚊", keywords: ["tram", "streetcar", "transport"] },
  { emoji: "🚝", keywords: ["monorail", "train", "transport"] },
  { emoji: "🚞", keywords: ["mountain", "railway", "train"] },
  { emoji: "🚋", keywords: ["tram", "car", "transport"] },
  { emoji: "🚌", keywords: ["bus", "transport", "vehicle"] },
  { emoji: "🚍", keywords: ["bus", "oncoming", "transport"] },
  { emoji: "🚎", keywords: ["trolley", "bus", "transport"] },
  { emoji: "🚐", keywords: ["minibus", "van", "transport"] },
  { emoji: "🚑", keywords: ["ambulance", "emergency", "medical"] },
  { emoji: "🚒", keywords: ["fire", "engine", "emergency"] },
  { emoji: "🚓", keywords: ["police", "car", "emergency"] },
  { emoji: "🚔", keywords: ["police", "car", "oncoming"] },
  { emoji: "🚕", keywords: ["taxi", "cab", "car"] },
  { emoji: "🚖", keywords: ["taxi", "oncoming", "cab"] },
  { emoji: "🚗", keywords: ["car", "drive", "vehicle", "auto"] },
  { emoji: "🚘", keywords: ["car", "oncoming", "vehicle"] },
  { emoji: "🚙", keywords: ["suv", "car", "vehicle"] },
  { emoji: "🛻", keywords: ["pickup", "truck", "vehicle"] },
  { emoji: "🚚", keywords: ["truck", "delivery", "vehicle"] },
  { emoji: "🚛", keywords: ["truck", "articulated", "lorry"] },
  { emoji: "🚜", keywords: ["tractor", "farm", "vehicle"] },
  { emoji: "🏎️", keywords: ["race", "car", "fast", "speed"] },
  { emoji: "🏍️", keywords: ["motorcycle", "racing", "bike"] },
  { emoji: "🛵", keywords: ["scooter", "motor", "vespa"] },
  { emoji: "🦽", keywords: ["wheelchair", "manual", "accessibility"] },
  { emoji: "🦼", keywords: ["wheelchair", "motorized", "accessibility"] },
  { emoji: "🛺", keywords: ["rickshaw", "auto", "tuktuk"] },
  { emoji: "🚲", keywords: ["bicycle", "bike", "cycle"] },
  { emoji: "🛴", keywords: ["scooter", "kick", "transport"] },
  { emoji: "🛹", keywords: ["skateboard", "skate", "board"] },
  { emoji: "🛼", keywords: ["roller", "skate", "skating"] },
  { emoji: "🚏", keywords: ["bus", "stop", "transport"] },
  { emoji: "🛣️", keywords: ["motorway", "highway", "road"] },
  { emoji: "🛤️", keywords: ["railway", "track", "train"] },
  { emoji: "🛢️", keywords: ["oil", "drum", "barrel"] },
  { emoji: "⛽", keywords: ["fuel", "pump", "gas", "petrol"] },
  { emoji: "🚨", keywords: ["police", "light", "emergency"] },
  { emoji: "🚥", keywords: ["traffic", "light", "horizontal"] },
  { emoji: "🚦", keywords: ["traffic", "light", "vertical"] },
  { emoji: "🛑", keywords: ["stop", "sign", "octagonal"] },
  { emoji: "🚧", keywords: ["construction", "barrier", "warning"] },
  { emoji: "⚓", keywords: ["anchor", "ship", "boat"] },
  { emoji: "⛵", keywords: ["sailboat", "boat", "sailing"] },
  { emoji: "🛶", keywords: ["canoe", "boat", "paddle"] },
  { emoji: "🚤", keywords: ["speedboat", "boat", "fast"] },
  { emoji: "🛳️", keywords: ["cruise", "ship", "passenger"] },
  { emoji: "⛴️", keywords: ["ferry", "boat", "ship"] },
  { emoji: "🛥️", keywords: ["boat", "motor", "yacht"] },
  { emoji: "🚢", keywords: ["ship", "boat", "cruise"] },
  { emoji: "✈️", keywords: ["plane", "airplane", "flight", "travel"] },
  { emoji: "🛩️", keywords: ["plane", "small", "aircraft"] },
  { emoji: "🛫", keywords: ["plane", "takeoff", "departure"] },
  { emoji: "🛬", keywords: ["plane", "landing", "arrival"] },
  { emoji: "🪂", keywords: ["parachute", "skydive", "fall"] },
  { emoji: "💺", keywords: ["seat", "airplane", "chair"] },
  { emoji: "🚁", keywords: ["helicopter", "fly", "aircraft"] },
  { emoji: "🚟", keywords: ["suspension", "railway", "transport"] },
  { emoji: "🚠", keywords: ["mountain", "cableway", "gondola"] },
  { emoji: "🚡", keywords: ["aerial", "tramway", "cable"] },
  { emoji: "🛰️", keywords: ["satellite", "space", "orbit"] },
  { emoji: "🚀", keywords: ["rocket", "space", "launch", "fast"] },
  { emoji: "🛸", keywords: ["ufo", "flying", "saucer", "alien"] },
  { emoji: "🛎️", keywords: ["bellhop", "bell", "hotel"] },
  { emoji: "🧳", keywords: ["luggage", "suitcase", "travel"] },
  { emoji: "⌛", keywords: ["hourglass", "time", "sand"] },
  { emoji: "⏳", keywords: ["hourglass", "flowing", "time"] },
  { emoji: "⌚", keywords: ["watch", "time", "wrist"] },
  { emoji: "⏰", keywords: ["clock", "time", "alarm"] },
  { emoji: "⏱️", keywords: ["stopwatch", "timer", "time"] },
  { emoji: "⏲️", keywords: ["timer", "clock", "time"] },
  { emoji: "🕰️", keywords: ["mantelpiece", "clock", "time"] },
  { emoji: "🕛", keywords: ["twelve", "oclock", "time"] },
  { emoji: "🕐", keywords: ["one", "oclock", "time"] },
  { emoji: "🌑", keywords: ["moon", "new", "phase"] },
  { emoji: "🌒", keywords: ["moon", "waxing", "crescent"] },
  { emoji: "🌓", keywords: ["moon", "first", "quarter"] },
  { emoji: "🌔", keywords: ["moon", "waxing", "gibbous"] },
  { emoji: "🌕", keywords: ["moon", "full", "phase"] },
  { emoji: "🌖", keywords: ["moon", "waning", "gibbous"] },
  { emoji: "🌗", keywords: ["moon", "last", "quarter"] },
  { emoji: "🌘", keywords: ["moon", "waning", "crescent"] },
  { emoji: "🌙", keywords: ["moon", "crescent", "night"] },
  { emoji: "🌚", keywords: ["moon", "face", "new"] },
  { emoji: "🌛", keywords: ["moon", "face", "first quarter"] },
  { emoji: "🌜", keywords: ["moon", "face", "last quarter"] },
  { emoji: "🌡️", keywords: ["thermometer", "temperature", "weather"] },
  { emoji: "☀️", keywords: ["sun", "sunny", "weather", "bright"] },
  { emoji: "🌝", keywords: ["moon", "face", "full"] },
  { emoji: "🌞", keywords: ["sun", "face", "bright"] },
  { emoji: "🪐", keywords: ["planet", "saturn", "ring"] },
  { emoji: "⭐", keywords: ["star", "favorite", "best"] },
  { emoji: "🌟", keywords: ["star", "sparkle", "shine", "special"] },
  { emoji: "🌠", keywords: ["shooting", "star", "falling"] },
  { emoji: "🌌", keywords: ["milky", "way", "galaxy", "stars"] },
  { emoji: "☁️", keywords: ["cloud", "weather", "sky"] },
  { emoji: "⛅", keywords: ["cloud", "sun", "weather"] },
  { emoji: "⛈️", keywords: ["storm", "thunder", "weather"] },
  { emoji: "🌤️", keywords: ["sun", "cloud", "small", "weather"] },
  { emoji: "🌥️", keywords: ["sun", "cloud", "large", "weather"] },
  { emoji: "🌦️", keywords: ["sun", "cloud", "rain", "weather"] },
  { emoji: "🌧️", keywords: ["rain", "cloud", "weather"] },
  { emoji: "🌨️", keywords: ["snow", "cloud", "weather"] },
  { emoji: "🌩️", keywords: ["lightning", "cloud", "weather"] },
  { emoji: "🌪️", keywords: ["tornado", "weather", "storm"] },
  { emoji: "🌫️", keywords: ["fog", "weather", "mist"] },
  { emoji: "🌬️", keywords: ["wind", "face", "blow"] },
  { emoji: "🌀", keywords: ["cyclone", "hurricane", "spiral"] },
  { emoji: "🌈", keywords: ["rainbow", "color", "weather"] },
  { emoji: "🌂", keywords: ["umbrella", "closed", "rain"] },
  { emoji: "☂️", keywords: ["umbrella", "rain", "weather"] },
  { emoji: "☔", keywords: ["umbrella", "rain", "drops"] },
  { emoji: "⛱️", keywords: ["umbrella", "beach", "ground"] },
  { emoji: "⚡", keywords: ["lightning", "thunder", "zap", "electric"] },
  { emoji: "❄️", keywords: ["snow", "winter", "cold", "ice"] },
  { emoji: "☃️", keywords: ["snowman", "winter", "snow"] },
  { emoji: "⛄", keywords: ["snowman", "winter", "snow"] },
  { emoji: "☄️", keywords: ["comet", "space", "shooting"] },
  { emoji: "🔥", keywords: ["fire", "hot", "flame", "lit"] },
  { emoji: "💧", keywords: ["water", "drop", "liquid"] },
  { emoji: "🌊", keywords: ["wave", "ocean", "sea", "water"] },
  
  // Objects
  { emoji: "👓", keywords: ["glasses", "eyeglasses", "spectacles"] },
  { emoji: "🕶️", keywords: ["sunglasses", "cool", "dark"] },
  { emoji: "🥽", keywords: ["goggles", "safety", "swim"] },
  { emoji: "🥼", keywords: ["lab", "coat", "doctor"] },
  { emoji: "🦺", keywords: ["safety", "vest", "construction"] },
  { emoji: "👔", keywords: ["tie", "necktie", "formal"] },
  { emoji: "👕", keywords: ["shirt", "tshirt", "clothing"] },
  { emoji: "👖", keywords: ["jeans", "pants", "clothing"] },
  { emoji: "🧣", keywords: ["scarf", "winter", "warm"] },
  { emoji: "🧤", keywords: ["gloves", "winter", "warm"] },
  { emoji: "🧥", keywords: ["coat", "jacket", "winter"] },
  { emoji: "🧦", keywords: ["socks", "feet", "clothing"] },
  { emoji: "👗", keywords: ["dress", "clothing", "fashion"] },
  { emoji: "👘", keywords: ["kimono", "japanese", "clothing"] },
  { emoji: "🥻", keywords: ["sari", "indian", "clothing"] },
  { emoji: "🩱", keywords: ["swimsuit", "one piece", "beach"] },
  { emoji: "🩲", keywords: ["briefs", "underwear", "shorts"] },
  { emoji: "🩳", keywords: ["shorts", "clothing", "summer"] },
  { emoji: "👙", keywords: ["bikini", "swimsuit", "beach"] },
  { emoji: "👚", keywords: ["blouse", "woman", "clothing"] },
  { emoji: "👛", keywords: ["purse", "wallet", "fashion"] },
  { emoji: "👜", keywords: ["handbag", "purse", "fashion"] },
  { emoji: "👝", keywords: ["pouch", "bag", "clutch"] },
  { emoji: "🛍️", keywords: ["bag", "shopping", "store", "buy"] },
  { emoji: "🎒", keywords: ["backpack", "school", "bag"] },
  { emoji: "🩴", keywords: ["thong", "sandal", "beach"] },
  { emoji: "👞", keywords: ["shoe", "man", "dress"] },
  { emoji: "👟", keywords: ["sneaker", "shoe", "athletic"] },
  { emoji: "🥾", keywords: ["hiking", "boot", "shoe"] },
  { emoji: "🥿", keywords: ["flat", "shoe", "ballet"] },
  { emoji: "👠", keywords: ["heel", "shoe", "woman"] },
  { emoji: "👡", keywords: ["sandal", "shoe", "woman"] },
  { emoji: "🩰", keywords: ["ballet", "shoes", "dance"] },
  { emoji: "👢", keywords: ["boot", "shoe", "woman"] },
  { emoji: "👑", keywords: ["crown", "royal", "king", "queen"] },
  { emoji: "👒", keywords: ["hat", "woman", "summer"] },
  { emoji: "🎩", keywords: ["hat", "top", "formal"] },
  { emoji: "🎓", keywords: ["graduation", "cap", "education"] },
  { emoji: "🧢", keywords: ["cap", "baseball", "hat"] },
  { emoji: "🪖", keywords: ["helmet", "military", "army"] },
  { emoji: "⛑️", keywords: ["helmet", "rescue", "white cross"] },
  { emoji: "📿", keywords: ["prayer", "beads", "rosary", "necklace"] },
  { emoji: "💄", keywords: ["lipstick", "makeup", "cosmetics"] },
  { emoji: "💍", keywords: ["ring", "diamond", "engaged", "wedding"] },
  { emoji: "💎", keywords: ["gem", "diamond", "jewel"] },
  { emoji: "🔇", keywords: ["mute", "speaker", "silent"] },
  { emoji: "🔈", keywords: ["speaker", "low", "volume"] },
  { emoji: "🔉", keywords: ["speaker", "medium", "volume"] },
  { emoji: "🔊", keywords: ["speaker", "loud", "volume"] },
  { emoji: "📢", keywords: ["megaphone", "announcement", "loud"] },
  { emoji: "📣", keywords: ["megaphone", "cheer", "announcement"] },
  { emoji: "📯", keywords: ["horn", "postal", "bugle"] },
  { emoji: "🔔", keywords: ["bell", "notification", "alert", "ring"] },
  { emoji: "🔕", keywords: ["bell", "mute", "silent"] },
  { emoji: "🎼", keywords: ["score", "musical", "notes"] },
  { emoji: "🎵", keywords: ["music", "song", "audio", "sound"] },
  { emoji: "🎶", keywords: ["notes", "music", "sound"] },
  { emoji: "🎙️", keywords: ["microphone", "studio", "podcast"] },
  { emoji: "🎚️", keywords: ["slider", "level", "control"] },
  { emoji: "🎛️", keywords: ["knobs", "control", "panel"] },
  { emoji: "🎤", keywords: ["microphone", "sing", "karaoke", "music"] },
  { emoji: "🎧", keywords: ["headphones", "music", "listen", "audio"] },
  { emoji: "📻", keywords: ["radio", "music", "listen"] },
  { emoji: "🎷", keywords: ["saxophone", "music", "jazz"] },
  { emoji: "🪗", keywords: ["accordion", "music", "instrument"] },
  { emoji: "🎸", keywords: ["guitar", "music", "rock", "instrument"] },
  { emoji: "🎹", keywords: ["piano", "keyboard", "music", "instrument"] },
  { emoji: "🎺", keywords: ["trumpet", "music", "brass", "instrument"] },
  { emoji: "🎻", keywords: ["violin", "music", "string", "instrument"] },
  { emoji: "🪕", keywords: ["banjo", "music", "instrument"] },
  { emoji: "🥁", keywords: ["drum", "music", "instrument"] },
  { emoji: "🪘", keywords: ["drum", "long", "instrument"] },
  { emoji: "📱", keywords: ["phone", "mobile", "cell"] },
  { emoji: "📲", keywords: ["phone", "arrow", "call"] },
  { emoji: "☎️", keywords: ["phone", "telephone", "call"] },
  { emoji: "📞", keywords: ["phone", "receiver", "call"] },
  { emoji: "📟", keywords: ["pager", "beeper", "device"] },
  { emoji: "📠", keywords: ["fax", "machine", "document"] },
  { emoji: "🔋", keywords: ["battery", "power", "charge"] },
  { emoji: "🔌", keywords: ["plug", "electric", "power"] },
  { emoji: "💻", keywords: ["computer", "laptop", "tech"] },
  { emoji: "🖥️", keywords: ["computer", "desktop", "screen"] },
  { emoji: "🖨️", keywords: ["printer", "print", "paper"] },
  { emoji: "⌨️", keywords: ["keyboard", "type", "computer"] },
  { emoji: "🖱️", keywords: ["mouse", "computer", "click"] },
  { emoji: "🖲️", keywords: ["trackball", "computer", "input"] },
  { emoji: "💽", keywords: ["disc", "computer", "minidisc"] },
  { emoji: "💾", keywords: ["floppy", "disk", "save"] },
  { emoji: "💿", keywords: ["cd", "disc", "optical"] },
  { emoji: "📀", keywords: ["dvd", "disc", "movie"] },
  { emoji: "🧮", keywords: ["abacus", "calculate", "math"] },
  { emoji: "🎥", keywords: ["movie", "camera", "film"] },
  { emoji: "🎞️", keywords: ["film", "frames", "movie"] },
  { emoji: "📽️", keywords: ["projector", "film", "movie"] },
  { emoji: "🎬", keywords: ["movie", "film", "video", "cinema"] },
  { emoji: "📺", keywords: ["tv", "television", "watch"] },
  { emoji: "📷", keywords: ["camera", "photo", "picture"] },
  { emoji: "📸", keywords: ["camera", "flash", "photo"] },
  { emoji: "📹", keywords: ["video", "camera", "record"] },
  { emoji: "📼", keywords: ["vhs", "tape", "video"] },
  { emoji: "🔍", keywords: ["search", "magnify", "look", "find"] },
  { emoji: "🔎", keywords: ["search", "magnify", "right"] },
  { emoji: "🕯️", keywords: ["candle", "light", "flame", "prayer"] },
  { emoji: "💡", keywords: ["light", "bulb", "idea", "bright"] },
  { emoji: "🔦", keywords: ["flashlight", "light", "torch"] },
  { emoji: "🏮", keywords: ["lantern", "red", "paper"] },
  { emoji: "🪔", keywords: ["lamp", "oil", "diya"] },
  { emoji: "📔", keywords: ["notebook", "decorative", "cover"] },
  { emoji: "📕", keywords: ["book", "closed", "red"] },
  { emoji: "📖", keywords: ["book", "read", "open"] },
  { emoji: "📗", keywords: ["book", "green", "closed"] },
  { emoji: "📘", keywords: ["book", "blue", "closed"] },
  { emoji: "📙", keywords: ["book", "orange", "closed"] },
  { emoji: "📚", keywords: ["book", "books", "read", "library", "education"] },
  { emoji: "📓", keywords: ["notebook", "journal", "diary"] },
  { emoji: "📒", keywords: ["ledger", "notebook", "yellow"] },
  { emoji: "📃", keywords: ["page", "curl", "document"] },
  { emoji: "📜", keywords: ["scroll", "paper", "document"] },
  { emoji: "📄", keywords: ["page", "document", "file"] },
  { emoji: "📰", keywords: ["newspaper", "news", "press"] },
  { emoji: "🗞️", keywords: ["newspaper", "rolled", "news"] },
  { emoji: "📑", keywords: ["bookmark", "tabs", "page"] },
  { emoji: "🔖", keywords: ["bookmark", "mark", "page"] },
  { emoji: "🏷️", keywords: ["label", "tag", "bookmark"] },
  { emoji: "💰", keywords: ["money", "bag", "dollar", "rich"] },
  { emoji: "🪙", keywords: ["coin", "money", "gold"] },
  { emoji: "💴", keywords: ["yen", "money", "japanese"] },
  { emoji: "💵", keywords: ["dollar", "money", "cash", "bill"] },
  { emoji: "💶", keywords: ["euro", "money", "cash"] },
  { emoji: "💷", keywords: ["pound", "money", "british"] },
  { emoji: "💸", keywords: ["money", "wings", "flying"] },
  { emoji: "💳", keywords: ["card", "credit", "payment", "buy"] },
  { emoji: "🧾", keywords: ["receipt", "purchase", "proof"] },
  { emoji: "💹", keywords: ["chart", "growth", "money"] },
  { emoji: "✉️", keywords: ["email", "mail", "letter", "envelope"] },
  { emoji: "📧", keywords: ["email", "mail", "electronic"] },
  { emoji: "📨", keywords: ["envelope", "incoming", "mail"] },
  { emoji: "📩", keywords: ["envelope", "arrow", "mail"] },
  { emoji: "📤", keywords: ["outbox", "tray", "send"] },
  { emoji: "📥", keywords: ["inbox", "tray", "receive"] },
  { emoji: "📦", keywords: ["package", "box", "delivery", "ship"] },
  { emoji: "📫", keywords: ["mailbox", "closed", "flag"] },
  { emoji: "📪", keywords: ["mailbox", "closed", "lowered"] },
  { emoji: "📬", keywords: ["mailbox", "open", "raised"] },
  { emoji: "📭", keywords: ["mailbox", "open", "lowered"] },
  { emoji: "📮", keywords: ["mailbox", "post", "mail"] },
  { emoji: "🗳️", keywords: ["ballot", "box", "vote"] },
  { emoji: "✏️", keywords: ["pencil", "write", "edit", "draw"] },
  { emoji: "✒️", keywords: ["pen", "nib", "write"] },
  { emoji: "🖋️", keywords: ["fountain", "pen", "write"] },
  { emoji: "🖊️", keywords: ["pen", "write", "ballpoint"] },
  { emoji: "🖌️", keywords: ["paintbrush", "art", "paint"] },
  { emoji: "🖍️", keywords: ["crayon", "draw", "color"] },
  { emoji: "📝", keywords: ["note", "memo", "write", "document"] },
  { emoji: "💼", keywords: ["briefcase", "business", "work"] },
  { emoji: "📁", keywords: ["folder", "file", "document"] },
  { emoji: "📂", keywords: ["folder", "open", "file"] },
  { emoji: "🗂️", keywords: ["folder", "divider", "organize"] },
  { emoji: "📅", keywords: ["calendar", "date", "schedule", "event"] },
  { emoji: "📆", keywords: ["calendar", "date", "schedule"] },
  { emoji: "🗒️", keywords: ["notepad", "spiral", "pad"] },
  { emoji: "🗓️", keywords: ["calendar", "schedule", "planner"] },
  { emoji: "📇", keywords: ["card", "index", "organize"] },
  { emoji: "📈", keywords: ["chart", "graph", "up", "increase"] },
  { emoji: "📉", keywords: ["chart", "graph", "down", "decrease"] },
  { emoji: "📊", keywords: ["chart", "graph", "data", "stats"] },
  { emoji: "📋", keywords: ["clipboard", "list", "document"] },
  { emoji: "📌", keywords: ["pin", "location", "pushpin"] },
  { emoji: "📍", keywords: ["pin", "location", "map", "place"] },
  { emoji: "📎", keywords: ["paperclip", "attach", "clip"] },
  { emoji: "🖇️", keywords: ["paperclips", "linked", "attach"] },
  { emoji: "📏", keywords: ["ruler", "straight", "measure"] },
  { emoji: "📐", keywords: ["ruler", "triangle", "measure"] },
  { emoji: "✂️", keywords: ["scissors", "cut", "snip"] },
  { emoji: "🗃️", keywords: ["card", "file", "box"] },
  { emoji: "🗄️", keywords: ["file", "cabinet", "storage"] },
  { emoji: "🗑️", keywords: ["trash", "wastebasket", "delete"] },
  { emoji: "🔐", keywords: ["lock", "key", "secure", "password"] },
  { emoji: "🔒", keywords: ["lock", "secure", "closed"] },
  { emoji: "🔓", keywords: ["lock", "unlock", "open"] },
  { emoji: "🔏", keywords: ["lock", "pen", "privacy"] },
  { emoji: "🔑", keywords: ["key", "lock", "password", "access"] },
  { emoji: "🗝️", keywords: ["key", "old", "antique"] },
  { emoji: "🔨", keywords: ["hammer", "tool", "build"] },
  { emoji: "🪓", keywords: ["axe", "tool", "chop"] },
  { emoji: "⛏️", keywords: ["pick", "tool", "mining"] },
  { emoji: "⚒️", keywords: ["hammer", "pick", "tools"] },
  { emoji: "🛠️", keywords: ["tools", "wrench", "hammer", "fix"] },
  { emoji: "🗡️", keywords: ["dagger", "sword", "knife"] },
  { emoji: "⚔️", keywords: ["swords", "crossed", "battle"] },
  { emoji: "🔫", keywords: ["gun", "pistol", "water"] },
  { emoji: "🪃", keywords: ["boomerang", "throw", "return"] },
  { emoji: "🏹", keywords: ["bow", "arrow", "archery"] },
  { emoji: "🛡️", keywords: ["shield", "protect", "defense"] },
  { emoji: "🪚", keywords: ["saw", "tool", "carpentry"] },
  { emoji: "🔧", keywords: ["wrench", "tool", "fix"] },
  { emoji: "🪛", keywords: ["screwdriver", "tool", "fix"] },
  { emoji: "🔩", keywords: ["nut", "bolt", "tool"] },
  { emoji: "⚙️", keywords: ["gear", "settings", "cog", "config"] },
  { emoji: "🗜️", keywords: ["clamp", "compress", "tool"] },
  { emoji: "⚖️", keywords: ["scale", "balance", "justice"] },
  { emoji: "🦯", keywords: ["cane", "white", "probing", "blind"] },
  { emoji: "🔗", keywords: ["link", "chain", "connect"] },
  { emoji: "⛓️", keywords: ["chains", "link", "connected"] },
  { emoji: "🪝", keywords: ["hook", "hang", "fishing"] },
  { emoji: "🧰", keywords: ["toolbox", "tools", "mechanic"] },
  { emoji: "🧲", keywords: ["magnet", "attract"] },
  { emoji: "🪜", keywords: ["ladder", "climb", "step"] },
  { emoji: "⚗️", keywords: ["alembic", "chemistry", "science"] },
  { emoji: "🧪", keywords: ["test", "tube", "science"] },
  { emoji: "🧫", keywords: ["petri", "dish", "science"] },
  { emoji: "🧬", keywords: ["dna", "genetics", "science"] },
  { emoji: "🔬", keywords: ["microscope", "science", "research"] },
  { emoji: "🔭", keywords: ["telescope", "astronomy", "space"] },
  { emoji: "📡", keywords: ["satellite", "antenna", "dish"] },
  { emoji: "💉", keywords: ["syringe", "needle", "injection", "vaccine"] },
  { emoji: "🩸", keywords: ["blood", "drop", "donate"] },
  { emoji: "💊", keywords: ["pill", "medicine", "drug"] },
  { emoji: "🩹", keywords: ["bandage", "adhesive", "heal"] },
  { emoji: "🩺", keywords: ["stethoscope", "doctor", "medical"] },
  { emoji: "🚪", keywords: ["door", "entrance", "exit"] },
  { emoji: "🛗", keywords: ["elevator", "lift", "accessibility"] },
  { emoji: "🪞", keywords: ["mirror", "reflection", "vanity"] },
  { emoji: "🪟", keywords: ["window", "frame", "view"] },
  { emoji: "🛏️", keywords: ["bed", "sleep", "bedroom"] },
  { emoji: "🛋️", keywords: ["couch", "sofa", "lamp"] },
  { emoji: "🪑", keywords: ["chair", "seat", "sit"] },
  { emoji: "🚽", keywords: ["toilet", "bathroom", "restroom"] },
  { emoji: "🪠", keywords: ["plunger", "toilet", "bathroom"] },
  { emoji: "🚿", keywords: ["shower", "bathroom", "water"] },
  { emoji: "🛁", keywords: ["bathtub", "bathroom", "bath"] },
  { emoji: "🪤", keywords: ["mouse", "trap", "catch"] },
  { emoji: "🪒", keywords: ["razor", "shave", "blade"] },
  { emoji: "🧴", keywords: ["lotion", "bottle", "skincare"] },
  { emoji: "🧷", keywords: ["safety", "pin", "diaper"] },
  { emoji: "🧹", keywords: ["broom", "sweep", "clean"] },
  { emoji: "🧺", keywords: ["basket", "laundry", "picnic"] },
  { emoji: "🧻", keywords: ["toilet", "paper", "roll"] },
  { emoji: "🪣", keywords: ["bucket", "pail", "water"] },
  { emoji: "🧼", keywords: ["soap", "bar", "clean"] },
  { emoji: "🪥", keywords: ["toothbrush", "dental", "hygiene"] },
  { emoji: "🧽", keywords: ["sponge", "clean", "porous"] },
  { emoji: "🧯", keywords: ["fire", "extinguisher", "emergency"] },
  { emoji: "🛒", keywords: ["cart", "shop", "shopping", "store", "buy"] },
  { emoji: "🚬", keywords: ["cigarette", "smoking"] },
  { emoji: "⚰️", keywords: ["coffin", "funeral", "death"] },
  { emoji: "🪦", keywords: ["headstone", "grave", "cemetery"] },
  { emoji: "⚱️", keywords: ["urn", "funeral", "ashes"] },
  { emoji: "🗿", keywords: ["moai", "statue", "easter island"] },
  { emoji: "🪧", keywords: ["placard", "sign", "protest"] },
  
  // Symbols
  { emoji: "🏧", keywords: ["atm", "bank", "money"] },
  { emoji: "🚮", keywords: ["litter", "trash", "bin"] },
  { emoji: "🚰", keywords: ["potable", "water", "tap"] },
  { emoji: "♿", keywords: ["wheelchair", "accessible", "disabled"] },
  { emoji: "🚹", keywords: ["men", "restroom", "bathroom"] },
  { emoji: "🚺", keywords: ["women", "restroom", "bathroom"] },
  { emoji: "🚻", keywords: ["restroom", "bathroom", "toilet"] },
  { emoji: "🚼", keywords: ["baby", "symbol", "changing"] },
  { emoji: "🚾", keywords: ["wc", "water", "closet", "toilet"] },
  { emoji: "🛂", keywords: ["passport", "control", "customs"] },
  { emoji: "🛃", keywords: ["customs", "airport", "travel"] },
  { emoji: "🛄", keywords: ["baggage", "claim", "luggage"] },
  { emoji: "🛅", keywords: ["left", "luggage", "storage"] },
  { emoji: "⚠️", keywords: ["warning", "caution", "alert"] },
  { emoji: "🚸", keywords: ["children", "crossing", "school"] },
  { emoji: "⛔", keywords: ["stop", "no entry", "forbidden"] },
  { emoji: "🚫", keywords: ["no", "forbidden", "prohibited"] },
  { emoji: "🚳", keywords: ["no", "bicycles", "prohibited"] },
  { emoji: "🚭", keywords: ["no", "smoking", "prohibited"] },
  { emoji: "🚯", keywords: ["no", "littering", "prohibited"] },
  { emoji: "🚱", keywords: ["non", "potable", "water"] },
  { emoji: "🚷", keywords: ["no", "pedestrians", "prohibited"] },
  { emoji: "📵", keywords: ["no", "mobile", "phones"] },
  { emoji: "🔞", keywords: ["no", "one", "under", "eighteen", "18"] },
  { emoji: "☢️", keywords: ["radioactive", "nuclear", "hazard"] },
  { emoji: "☣️", keywords: ["biohazard", "biological", "hazard"] },
  { emoji: "⬆️", keywords: ["up", "arrow", "direction"] },
  { emoji: "↗️", keywords: ["up", "right", "arrow"] },
  { emoji: "➡️", keywords: ["right", "arrow", "direction"] },
  { emoji: "↘️", keywords: ["down", "right", "arrow"] },
  { emoji: "⬇️", keywords: ["down", "arrow", "direction"] },
  { emoji: "↙️", keywords: ["down", "left", "arrow"] },
  { emoji: "⬅️", keywords: ["left", "arrow", "direction"] },
  { emoji: "↖️", keywords: ["up", "left", "arrow"] },
  { emoji: "↕️", keywords: ["up", "down", "arrow"] },
  { emoji: "↔️", keywords: ["left", "right", "arrow"] },
  { emoji: "↩️", keywords: ["back", "arrow", "return"] },
  { emoji: "↪️", keywords: ["forward", "arrow", "right"] },
  { emoji: "⤴️", keywords: ["up", "arrow", "curving"] },
  { emoji: "⤵️", keywords: ["down", "arrow", "curving"] },
  { emoji: "🔃", keywords: ["clockwise", "arrows", "reload"] },
  { emoji: "🔄", keywords: ["counterclockwise", "arrows", "refresh"] },
  { emoji: "🔙", keywords: ["back", "arrow", "return"] },
  { emoji: "🔚", keywords: ["end", "arrow"] },
  { emoji: "🔛", keywords: ["on", "arrow"] },
  { emoji: "🔜", keywords: ["soon", "arrow"] },
  { emoji: "🔝", keywords: ["top", "arrow", "up"] },
  { emoji: "🛐", keywords: ["place", "worship", "religion"] },
  { emoji: "⚛️", keywords: ["atom", "science", "symbol"] },
  { emoji: "🕉️", keywords: ["om", "hindu", "religion"] },
  { emoji: "✡️", keywords: ["star", "david", "jewish"] },
  { emoji: "☸️", keywords: ["wheel", "dharma", "buddhism"] },
  { emoji: "☯️", keywords: ["yin", "yang", "balance"] },
  { emoji: "✝️", keywords: ["cross", "christian", "religion", "faith", "jesus"] },
  { emoji: "☦️", keywords: ["orthodox", "cross", "christian"] },
  { emoji: "☪️", keywords: ["star", "crescent", "islam"] },
  { emoji: "☮️", keywords: ["peace", "symbol", "love"] },
  { emoji: "🕎", keywords: ["menorah", "hanukkah", "jewish"] },
  { emoji: "🔯", keywords: ["star", "six", "pointed"] },
  { emoji: "♈", keywords: ["aries", "zodiac", "ram"] },
  { emoji: "♉", keywords: ["taurus", "zodiac", "bull"] },
  { emoji: "♊", keywords: ["gemini", "zodiac", "twins"] },
  { emoji: "♋", keywords: ["cancer", "zodiac", "crab"] },
  { emoji: "♌", keywords: ["leo", "zodiac", "lion"] },
  { emoji: "♍", keywords: ["virgo", "zodiac", "maiden"] },
  { emoji: "♎", keywords: ["libra", "zodiac", "scales"] },
  { emoji: "♏", keywords: ["scorpio", "zodiac", "scorpion"] },
  { emoji: "♐", keywords: ["sagittarius", "zodiac", "archer"] },
  { emoji: "♑", keywords: ["capricorn", "zodiac", "goat"] },
  { emoji: "♒", keywords: ["aquarius", "zodiac", "water"] },
  { emoji: "♓", keywords: ["pisces", "zodiac", "fish"] },
  { emoji: "⛎", keywords: ["ophiuchus", "zodiac", "serpent"] },
  { emoji: "🔀", keywords: ["shuffle", "twisted", "arrows"] },
  { emoji: "🔁", keywords: ["repeat", "loop", "arrows"] },
  { emoji: "🔂", keywords: ["repeat", "one", "track"] },
  { emoji: "▶️", keywords: ["play", "button", "start"] },
  { emoji: "⏩", keywords: ["fast", "forward", "skip"] },
  { emoji: "⏭️", keywords: ["next", "track", "skip"] },
  { emoji: "⏯️", keywords: ["play", "pause", "button"] },
  { emoji: "◀️", keywords: ["reverse", "button", "back"] },
  { emoji: "⏪", keywords: ["rewind", "fast", "back"] },
  { emoji: "⏮️", keywords: ["previous", "track", "back"] },
  { emoji: "🔼", keywords: ["up", "button", "triangle"] },
  { emoji: "⏫", keywords: ["fast", "up", "button"] },
  { emoji: "🔽", keywords: ["down", "button", "triangle"] },
  { emoji: "⏬", keywords: ["fast", "down", "button"] },
  { emoji: "⏸️", keywords: ["pause", "button", "stop"] },
  { emoji: "⏹️", keywords: ["stop", "button", "square"] },
  { emoji: "⏺️", keywords: ["record", "button", "circle"] },
  { emoji: "⏏️", keywords: ["eject", "button"] },
  { emoji: "🎦", keywords: ["cinema", "movie", "film"] },
  { emoji: "🔅", keywords: ["dim", "brightness", "low"] },
  { emoji: "🔆", keywords: ["bright", "brightness", "high"] },
  { emoji: "📶", keywords: ["signal", "bars", "antenna"] },
  { emoji: "📳", keywords: ["vibration", "mode", "phone"] },
  { emoji: "📴", keywords: ["off", "phone", "mobile"] },
  { emoji: "♀️", keywords: ["female", "woman", "symbol"] },
  { emoji: "♂️", keywords: ["male", "man", "symbol"] },
  { emoji: "⚧️", keywords: ["transgender", "symbol", "gender"] },
  { emoji: "✖️", keywords: ["multiply", "x", "times"] },
  { emoji: "➕", keywords: ["plus", "add", "new"] },
  { emoji: "➖", keywords: ["minus", "subtract", "remove"] },
  { emoji: "➗", keywords: ["divide", "division", "math"] },
  { emoji: "♾️", keywords: ["infinity", "forever", "endless"] },
  { emoji: "‼️", keywords: ["exclamation", "double", "bangbang"] },
  { emoji: "⁉️", keywords: ["exclamation", "question", "interrobang"] },
  { emoji: "❓", keywords: ["question", "help", "ask"] },
  { emoji: "❔", keywords: ["question", "white"] },
  { emoji: "❗", keywords: ["exclamation", "important", "alert"] },
  { emoji: "❕", keywords: ["exclamation", "white"] },
  { emoji: "〰️", keywords: ["wavy", "dash", "line"] },
  { emoji: "💱", keywords: ["currency", "exchange", "money"] },
  { emoji: "💲", keywords: ["dollar", "money", "sign"] },
  { emoji: "⚕️", keywords: ["medical", "symbol", "staff"] },
  { emoji: "♻️", keywords: ["recycle", "green", "environment"] },
  { emoji: "⚜️", keywords: ["fleur", "de", "lis"] },
  { emoji: "🔱", keywords: ["trident", "poseidon", "emblem"] },
  { emoji: "📛", keywords: ["name", "badge", "tag"] },
  { emoji: "🔰", keywords: ["beginner", "japanese", "symbol"] },
  { emoji: "⭕", keywords: ["circle", "o", "ring"] },
  { emoji: "✅", keywords: ["check", "yes", "done", "complete"] },
  { emoji: "☑️", keywords: ["check", "box", "vote"] },
  { emoji: "✔️", keywords: ["check", "tick", "yes", "correct"] },
  { emoji: "❌", keywords: ["x", "cross", "no", "wrong", "delete"] },
  { emoji: "❎", keywords: ["x", "cross", "mark", "no"] },
  { emoji: "➰", keywords: ["curly", "loop", "curl"] },
  { emoji: "➿", keywords: ["double", "curly", "loop"] },
  { emoji: "〽️", keywords: ["part", "alternation", "mark"] },
  { emoji: "✳️", keywords: ["eight", "spoked", "asterisk"] },
  { emoji: "✴️", keywords: ["eight", "pointed", "star"] },
  { emoji: "❇️", keywords: ["sparkle", "stars"] },
  { emoji: "©️", keywords: ["copyright", "symbol", "c"] },
  { emoji: "®️", keywords: ["registered", "symbol", "trademark"] },
  { emoji: "™️", keywords: ["trademark", "symbol", "tm"] },
  { emoji: "#️⃣", keywords: ["hashtag", "number", "pound"] },
  { emoji: "*️⃣", keywords: ["keycap", "asterisk", "star"] },
  { emoji: "0️⃣", keywords: ["zero", "keycap", "0"] },
  { emoji: "1️⃣", keywords: ["one", "keycap", "1"] },
  { emoji: "2️⃣", keywords: ["two", "keycap", "2"] },
  { emoji: "3️⃣", keywords: ["three", "keycap", "3"] },
  { emoji: "4️⃣", keywords: ["four", "keycap", "4"] },
  { emoji: "5️⃣", keywords: ["five", "keycap", "5"] },
  { emoji: "6️⃣", keywords: ["six", "keycap", "6"] },
  { emoji: "7️⃣", keywords: ["seven", "keycap", "7"] },
  { emoji: "8️⃣", keywords: ["eight", "keycap", "8"] },
  { emoji: "9️⃣", keywords: ["nine", "keycap", "9"] },
  { emoji: "🔟", keywords: ["ten", "keycap", "10"] },
  { emoji: "🔢", keywords: ["numbers", "123", "count"] },
  { emoji: "🔣", keywords: ["symbols", "input", "characters"] },
  { emoji: "🔤", keywords: ["letters", "abc", "alphabet"] },
  { emoji: "🔠", keywords: ["letters", "uppercase", "capital"] },
  { emoji: "🔡", keywords: ["letters", "lowercase", "small"] },
  { emoji: "🅰️", keywords: ["a", "blood", "type"] },
  { emoji: "🆎", keywords: ["ab", "blood", "type"] },
  { emoji: "🅱️", keywords: ["b", "blood", "type"] },
  { emoji: "🆑", keywords: ["cl", "clear", "button"] },
  { emoji: "🆒", keywords: ["cool", "button", "word"] },
  { emoji: "🆓", keywords: ["free", "gratis"] },
  { emoji: "ℹ️", keywords: ["info", "information", "help"] },
  { emoji: "🆔", keywords: ["id", "identity", "button"] },
  { emoji: "Ⓜ️", keywords: ["m", "circled", "metro"] },
  { emoji: "🆕", keywords: ["new", "fresh", "latest"] },
  { emoji: "🆖", keywords: ["ng", "no good", "button"] },
  { emoji: "🅾️", keywords: ["o", "blood", "type"] },
  { emoji: "🆗", keywords: ["ok", "okay", "button"] },
  { emoji: "🅿️", keywords: ["p", "parking", "button"] },
  { emoji: "🆘", keywords: ["sos", "help", "emergency"] },
  { emoji: "🆙", keywords: ["up", "button", "level"] },
  { emoji: "🆚", keywords: ["vs", "versus", "button"] },
  { emoji: "🈁", keywords: ["koko", "japanese", "here"] },
  { emoji: "🈂️", keywords: ["sa", "japanese", "service"] },
  { emoji: "🔴", keywords: ["red", "circle", "dot"] },
  { emoji: "🟠", keywords: ["orange", "circle", "dot"] },
  { emoji: "🟡", keywords: ["yellow", "circle", "dot"] },
  { emoji: "🟢", keywords: ["green", "circle", "dot"] },
  { emoji: "🔵", keywords: ["blue", "circle", "dot"] },
  { emoji: "🟣", keywords: ["purple", "circle", "dot"] },
  { emoji: "🟤", keywords: ["brown", "circle", "dot"] },
  { emoji: "⚫", keywords: ["black", "circle", "dot"] },
  { emoji: "⚪", keywords: ["white", "circle", "dot"] },
  { emoji: "🟥", keywords: ["red", "square"] },
  { emoji: "🟧", keywords: ["orange", "square"] },
  { emoji: "🟨", keywords: ["yellow", "square"] },
  { emoji: "🟩", keywords: ["green", "square"] },
  { emoji: "🟦", keywords: ["blue", "square"] },
  { emoji: "🟪", keywords: ["purple", "square"] },
  { emoji: "🟫", keywords: ["brown", "square"] },
  { emoji: "⬛", keywords: ["black", "large", "square"] },
  { emoji: "⬜", keywords: ["white", "large", "square"] },
  { emoji: "◼️", keywords: ["black", "medium", "square"] },
  { emoji: "◻️", keywords: ["white", "medium", "square"] },
  { emoji: "◾", keywords: ["black", "medium small", "square"] },
  { emoji: "◽", keywords: ["white", "medium small", "square"] },
  { emoji: "▪️", keywords: ["black", "small", "square"] },
  { emoji: "▫️", keywords: ["white", "small", "square"] },
  { emoji: "🔶", keywords: ["orange", "diamond", "large"] },
  { emoji: "🔷", keywords: ["blue", "diamond", "large"] },
  { emoji: "🔸", keywords: ["orange", "diamond", "small"] },
  { emoji: "🔹", keywords: ["blue", "diamond", "small"] },
  { emoji: "🔺", keywords: ["red", "triangle", "up"] },
  { emoji: "🔻", keywords: ["red", "triangle", "down"] },
  { emoji: "💠", keywords: ["diamond", "cute", "flower"] },
  { emoji: "🔘", keywords: ["radio", "button", "option"] },
  { emoji: "🔳", keywords: ["white", "square", "button"] },
  { emoji: "🔲", keywords: ["black", "square", "button"] },
  
  // Flags
  { emoji: "🏁", keywords: ["flag", "checkered", "finish", "race"] },
  { emoji: "🚩", keywords: ["flag", "red", "mark"] },
  { emoji: "🎌", keywords: ["flag", "japan", "crossed"] },
  { emoji: "🏴", keywords: ["flag", "black"] },
  { emoji: "🏳️", keywords: ["flag", "white", "surrender"] },
  { emoji: "🏳️‍🌈", keywords: ["rainbow", "flag", "pride", "lgbtq"] },
  { emoji: "🏳️‍⚧️", keywords: ["transgender", "flag", "pride"] },
  { emoji: "🏴‍☠️", keywords: ["pirate", "flag", "jolly roger"] },
  { emoji: "🇺🇸", keywords: ["flag", "usa", "america", "united states"] },
  { emoji: "🇬🇧", keywords: ["flag", "uk", "britain", "united kingdom"] },
  { emoji: "🇨🇦", keywords: ["flag", "canada", "maple"] },
  { emoji: "🇦🇺", keywords: ["flag", "australia"] },
  { emoji: "🇫🇷", keywords: ["flag", "france", "french"] },
  { emoji: "🇩🇪", keywords: ["flag", "germany", "german"] },
  { emoji: "🇮🇹", keywords: ["flag", "italy", "italian"] },
  { emoji: "🇪🇸", keywords: ["flag", "spain", "spanish"] },
  { emoji: "🇯🇵", keywords: ["flag", "japan", "japanese"] },
  { emoji: "🇨🇳", keywords: ["flag", "china", "chinese"] },
  { emoji: "🇰🇷", keywords: ["flag", "korea", "south", "korean"] },
  { emoji: "🇮🇳", keywords: ["flag", "india", "indian"] },
  { emoji: "🇧🇷", keywords: ["flag", "brazil", "brazilian"] },
  { emoji: "🇲🇽", keywords: ["flag", "mexico", "mexican"] },
  { emoji: "🇷🇺", keywords: ["flag", "russia", "russian"] },
  { emoji: "🔝", keywords: ["top", "arrow", "up"] },
  { emoji: "⬆️", keywords: ["up", "arrow", "north"] },
  { emoji: "⬇️", keywords: ["down", "arrow", "south"] },
  { emoji: "⬅️", keywords: ["left", "arrow", "west"] },
  { emoji: "➡️", keywords: ["right", "arrow", "east"] },
  { emoji: "↗️", keywords: ["arrow", "northeast", "up right"] },
  { emoji: "↘️", keywords: ["arrow", "southeast", "down right"] },
  { emoji: "↙️", keywords: ["arrow", "southwest", "down left"] },
  { emoji: "↖️", keywords: ["arrow", "northwest", "up left"] },
  { emoji: "↕️", keywords: ["arrow", "up down", "vertical"] },
  { emoji: "↔️", keywords: ["arrow", "left right", "horizontal"] },
  { emoji: "🔀", keywords: ["shuffle", "random", "mix"] },
  { emoji: "🔁", keywords: ["repeat", "loop", "replay"] },
  { emoji: "🔂", keywords: ["repeat", "one", "single"] },
  { emoji: "▶️", keywords: ["play", "start", "forward"] },
  { emoji: "⏸️", keywords: ["pause", "stop", "wait"] },
  { emoji: "⏹️", keywords: ["stop", "end"] },
  { emoji: "⏺️", keywords: ["record", "dot"] },
  { emoji: "⏭️", keywords: ["next", "forward", "skip"] },
  { emoji: "⏮️", keywords: ["previous", "back", "rewind"] },
  { emoji: "🔴", keywords: ["red", "circle", "dot"] },
  { emoji: "🟠", keywords: ["orange", "circle", "dot"] },
  { emoji: "🟡", keywords: ["yellow", "circle", "dot"] },
  { emoji: "🟢", keywords: ["green", "circle", "dot"] },
  { emoji: "🔵", keywords: ["blue", "circle", "dot"] },
  { emoji: "🟣", keywords: ["purple", "circle", "dot"] },
  { emoji: "🟤", keywords: ["brown", "circle", "dot"] },
  { emoji: "⚫", keywords: ["black", "circle", "dot"] },
  { emoji: "⚪", keywords: ["white", "circle", "dot"] },
  { emoji: "🟥", keywords: ["red", "square"] },
  { emoji: "🟧", keywords: ["orange", "square"] },
  { emoji: "🟨", keywords: ["yellow", "square"] },
  { emoji: "🟩", keywords: ["green", "square"] },
  { emoji: "🟦", keywords: ["blue", "square"] },
  { emoji: "🟪", keywords: ["purple", "square"] },
  { emoji: "🟫", keywords: ["brown", "square"] },
  { emoji: "⬛", keywords: ["black", "square"] },
  { emoji: "⬜", keywords: ["white", "square"] },
  { emoji: "👨‍👩‍👧", keywords: ["family", "parents", "child"] },
  { emoji: "👨‍👩‍👦", keywords: ["family", "parents", "child", "boy"] },
  { emoji: "👪", keywords: ["family", "parents", "child"] },
  { emoji: "👥", keywords: ["people", "group", "community"] },
  { emoji: "👤", keywords: ["person", "user", "profile"] },
  { emoji: "🧑‍🤝‍🧑", keywords: ["people", "holding hands", "together"] },
  { emoji: "👫", keywords: ["couple", "holding hands", "together"] },
  { emoji: "👭", keywords: ["women", "holding hands", "friends"] },
  { emoji: "👬", keywords: ["men", "holding hands", "friends"] },
  { emoji: "🧑‍🦱", keywords: ["person", "curly hair"] },
  { emoji: "🧑‍🦰", keywords: ["person", "red hair", "ginger"] },
  { emoji: "🧑‍🦳", keywords: ["person", "white hair", "gray"] },
  { emoji: "🧑‍🦲", keywords: ["person", "bald"] },
  { emoji: "👶", keywords: ["baby", "child", "infant"] },
  { emoji: "🧒", keywords: ["child", "kid", "young"] },
  { emoji: "👦", keywords: ["boy", "child", "young"] },
  { emoji: "👧", keywords: ["girl", "child", "young"] },
  { emoji: "🧑", keywords: ["person", "adult"] },
  { emoji: "👨", keywords: ["man", "adult", "male"] },
  { emoji: "👩", keywords: ["woman", "adult", "female"] },
  { emoji: "🧓", keywords: ["older", "adult", "elder"] },
  { emoji: "👴", keywords: ["old", "man", "grandfather"] },
  { emoji: "👵", keywords: ["old", "woman", "grandmother"] },
  { emoji: "🧑‍⚕️", keywords: ["doctor", "health", "medical", "nurse"] },
  { emoji: "👨‍⚕️", keywords: ["doctor", "man", "health"] },
  { emoji: "👩‍⚕️", keywords: ["doctor", "woman", "health"] },
  { emoji: "🧑‍🎓", keywords: ["student", "graduate", "education"] },
  { emoji: "👨‍🎓", keywords: ["student", "man", "graduate"] },
  { emoji: "👩‍🎓", keywords: ["student", "woman", "graduate"] },
  { emoji: "🧑‍🏫", keywords: ["teacher", "education", "professor"] },
  { emoji: "👨‍🏫", keywords: ["teacher", "man", "professor"] },
  { emoji: "👩‍🏫", keywords: ["teacher", "woman", "professor"] },
  { emoji: "🧑‍🍳", keywords: ["chef", "cook", "food"] },
  { emoji: "👨‍🍳", keywords: ["chef", "man", "cook"] },
  { emoji: "👩‍🍳", keywords: ["chef", "woman", "cook"] },
  { emoji: "🧑‍🎨", keywords: ["artist", "paint", "creative"] },
  { emoji: "👨‍🎨", keywords: ["artist", "man", "paint"] },
  { emoji: "👩‍🎨", keywords: ["artist", "woman", "paint"] },
  { emoji: "🧑‍💻", keywords: ["technologist", "computer", "developer", "programmer"] },
  { emoji: "👨‍💻", keywords: ["technologist", "man", "computer"] },
  { emoji: "👩‍💻", keywords: ["technologist", "woman", "computer"] },
  { emoji: "🧑‍🔬", keywords: ["scientist", "research", "lab"] },
  { emoji: "👨‍🔬", keywords: ["scientist", "man", "research"] },
  { emoji: "👩‍🔬", keywords: ["scientist", "woman", "research"] },
  { emoji: "🧑‍🚀", keywords: ["astronaut", "space", "rocket"] },
  { emoji: "👨‍🚀", keywords: ["astronaut", "man", "space"] },
  { emoji: "👩‍🚀", keywords: ["astronaut", "woman", "space"] },
  { emoji: "🧑‍🚒", keywords: ["firefighter", "fire", "rescue"] },
  { emoji: "👨‍🚒", keywords: ["firefighter", "man", "fire"] },
  { emoji: "👩‍🚒", keywords: ["firefighter", "woman", "fire"] },
  { emoji: "👮", keywords: ["police", "officer", "cop"] },
  { emoji: "🦸", keywords: ["superhero", "hero", "power"] },
  { emoji: "🦹", keywords: ["supervillain", "villain", "evil"] },
  { emoji: "🧙", keywords: ["mage", "wizard", "magic"] },
  { emoji: "🧚", keywords: ["fairy", "magic", "fantasy"] },
  { emoji: "🧛", keywords: ["vampire", "dracula", "halloween"] },
  { emoji: "🧜", keywords: ["merperson", "mermaid", "ocean"] },
  { emoji: "🧝", keywords: ["elf", "fantasy", "magic"] },
  { emoji: "🧞", keywords: ["genie", "magic", "wish"] },
  { emoji: "🧟", keywords: ["zombie", "undead", "halloween"] },
  { emoji: "👻", keywords: ["ghost", "halloween", "spooky"] },
  { emoji: "💀", keywords: ["skull", "death", "skeleton"] },
  { emoji: "☠️", keywords: ["skull", "crossbones", "danger"] },
  { emoji: "👽", keywords: ["alien", "space", "ufo"] },
  { emoji: "👾", keywords: ["alien", "monster", "game"] },
  { emoji: "🤖", keywords: ["robot", "machine", "android"] },
  { emoji: "🎃", keywords: ["pumpkin", "halloween", "jack-o-lantern"] },
  { emoji: "😈", keywords: ["devil", "smile", "purple"] },
  { emoji: "👿", keywords: ["devil", "angry", "imp"] },
  { emoji: "👹", keywords: ["ogre", "monster", "red"] },
  { emoji: "👺", keywords: ["goblin", "monster", "red"] },
  { emoji: "💩", keywords: ["poop", "poo", "pile"] },
  { emoji: "🤡", keywords: ["clown", "face", "circus"] },
  { emoji: "🛡️", keywords: ["shield", "protect", "defense"] },
  { emoji: "⚔️", keywords: ["sword", "crossed", "battle"] },
  { emoji: "🗡️", keywords: ["dagger", "knife", "weapon"] },
  { emoji: "🏹", keywords: ["bow", "arrow", "archery"] },
  { emoji: "🔮", keywords: ["crystal", "ball", "fortune", "magic"] },
  { emoji: "💎", keywords: ["gem", "diamond", "jewel", "precious"] },
  { emoji: "👑", keywords: ["crown", "king", "queen", "royal"] },
  { emoji: "💍", keywords: ["ring", "wedding", "engaged", "diamond"] },
  { emoji: "👓", keywords: ["glasses", "eyeglasses", "spectacles"] },
  { emoji: "🕶️", keywords: ["sunglasses", "cool", "shades"] },
  { emoji: "🎒", keywords: ["backpack", "bag", "school"] },
  { emoji: "👜", keywords: ["handbag", "purse", "bag"] },
  { emoji: "👛", keywords: ["purse", "wallet", "money"] },
  { emoji: "👝", keywords: ["pouch", "bag", "clutch"] },
  { emoji: "🧳", keywords: ["luggage", "suitcase", "travel"] },
  { emoji: "🌂", keywords: ["umbrella", "closed", "rain"] },
  { emoji: "☂️", keywords: ["umbrella", "rain", "weather"] },
  { emoji: "🎀", keywords: ["ribbon", "bow", "gift", "pink"] },
  { emoji: "🧸", keywords: ["teddy", "bear", "toy", "stuffed"] },
  { emoji: "🪀", keywords: ["yo-yo", "toy", "play"] },
  { emoji: "🪁", keywords: ["kite", "fly", "wind"] },
  { emoji: "🛸", keywords: ["ufo", "flying", "saucer", "alien"] },
  { emoji: "🚨", keywords: ["siren", "police", "emergency", "light"] },
  { emoji: "🔆", keywords: ["bright", "sun", "high", "brightness"] },
  { emoji: "🔅", keywords: ["dim", "low", "brightness"] },
];

interface EmojiPickerProps {
  value: string | null | undefined;
  onChange: (emoji: string | null) => void;
  placeholder?: string;
  title?: string;
}

export function EmojiPicker({ value, onChange, placeholder = "Select emoji", title }: EmojiPickerProps) {
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");

  const filteredEmojis = useMemo(() => {
    if (!search.trim()) {
      return EMOJI_DATA.slice(0, 50); // Show first 50 when no search
    }
    const searchLower = search.toLowerCase();
    return EMOJI_DATA.filter(
      (item) =>
        item.keywords.some((keyword) => keyword.includes(searchLower)) ||
        item.emoji.includes(search)
    );
  }, [search]);

  const handleSelect = (emoji: string) => {
    onChange(emoji);
    setOpen(false);
    setSearch("");
  };

  const handleClear = (e: React.MouseEvent) => {
    e.stopPropagation();
    onChange(null);
  };

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          className="w-full justify-between text-lg h-10"
          title={title}
        >
          {value ? (
            <span className="flex items-center gap-2">
              <span>{value}</span>
              <X
                className="h-3 w-3 text-muted-foreground hover:text-foreground"
                onClick={handleClear}
              />
            </span>
          ) : (
            <span className="text-muted-foreground text-sm">{placeholder}</span>
          )}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-72 p-2 z-50" align="start">
        <Input
          placeholder="Search emojis (e.g., home, star, heart)..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="mb-2"
          autoFocus
        />
        <ScrollArea className="h-48">
          {filteredEmojis.length > 0 ? (
            <div className="grid grid-cols-6 gap-1">
              {filteredEmojis.map((item, index) => (
                <Button
                  key={`${item.emoji}-${index}`}
                  variant="ghost"
                  className="h-9 w-9 p-0 text-xl hover:bg-accent"
                  onClick={() => handleSelect(item.emoji)}
                  title={item.keywords.join(", ")}
                >
                  {item.emoji}
                </Button>
              ))}
            </div>
          ) : (
            <div className="text-center text-muted-foreground text-sm py-4">
              No emojis found for "{search}"
            </div>
          )}
        </ScrollArea>
      </PopoverContent>
    </Popover>
  );
}
